"""System/platform blocks: identity, services, access, extra config.

Each vendor method is a faithful translation of its template stanza
and must stay byte-identical to it (tests/golden/). Blank separator
lines are part of the contract: the templates emit them
unconditionally between sections, so blocks emit their own trailing
separators exactly where the template put them.
"""

from typing import List

from barf.configs.base import ConfigBlock, secret_value
from barf.configs.lines import ros_line


class Header(ConfigBlock):
    """The rendered file's preamble, where the format needs one.

    VyOS set-commands need no header; RouterOS gets an explanatory
    comment block and linux the shell-script plumbing its heredoc
    encoding rides on.
    """

    def mikrotik(self) -> List[str]:
        return [
            f"# {self.host.hostname} - generated by barf. RouterOS v7 CLI.",
            "# Sections mirror the fabric contract the VyOS/linux hosts implement:",
            "# WireGuard links, link addresses, eBGP to every spine, announced",
            "# networks, and geographic path weighting (origin-site large",
            "# communities in, local-pref out) when the host has a `site`.",
        ]

    def linux(self) -> List[str]:
        return [
            "#!/bin/sh",
            f"# Rendered by barf for {self.host.hostname}.",
            "#",
            "# One quoted heredoc per barf-owned file. `barf config diff|deploy`",
            "# parses these BARF_FILE blocks into a path -> content map and manages",
            "# the files over SSH; running this script by hand writes the exact",
            "# same contents (the delimiter is quoted, so nothing expands).",
            "set -e",
            "mkdir -p /etc/wireguard /etc/network/interfaces.d /etc/bird/conf.d",
            "",
        ]


class SystemConfig(ConfigBlock):
    """System basics: identity, SNMP, DNS, syslog, conntrack."""

    def vyos(self) -> List[str]:
        gm = self.ctx.global_meta
        lines = [
            f"set system host-name '{self.host.hostname}'",
            f"set system domain-name '{gm.get('search_domain', '')}'",
            "set system login user supertech authentication"
            f" plaintext-password '{self.host.admin_password}'",
            f"set service snmp community '{gm.get('snmp_public', '')}'"
            " authorization 'ro'",
        ]
        location = self.host.snmp_location or gm.get("snmp_location", "")
        if location:
            lines.append(f"set service snmp location '{location}'")
        lines.append(f"set service snmp contact '{gm.get('snmp_contact', '')}'")
        for dns_server in self.host.nameservers:
            lines.append(f"set system name-server '{dns_server}'")
        lines += [
            "",
            # The factory-default empty loopback node; rendering it
            # keeps the owned diff clean instead of fighting the
            # default on every image.
            "set interfaces loopback lo",
            "",
            "set system syslog local facility all level info",
            "set system syslog local facility local7 level debug",
            "set system console device ttyS0 speed 115200",
            "set system config-management commit-revisions 100",
            "",
        ]
        # Conntrack helpers: the vyatta-era defaults, set explicitly.
        for module in ["ftp", "h323", "nfs", "pptp", "sip", "sqlnet", "tftp"]:
            lines.append(f"set system conntrack modules {module}")
        return lines


class SshConfig(ConfigBlock):
    """The fleet ssh_keys, loaded onto each vendor's admin account.

    VyOS/linux attach them to the fleet-standard supertech user;
    RouterOS has no supertech, so keys land on ``admin``
    (MIKROTIK_SSH_USER). RouterOS never reads key material back
    (write-only in the diff), so rotating a key must also change its
    trailing comment (the key-owner identity).
    """

    MIKROTIK_SSH_USER = "admin"

    def mikrotik(self) -> List[str]:
        lines = []
        for ssh_key in self.ctx.global_meta.get("ssh_keys", []):
            lines.append(
                ros_line(
                    "/user/ssh-keys",
                    "add",
                    {
                        "user": self.MIKROTIK_SSH_USER,
                        "key-owner": ssh_key.split(" ")[2],
                        "key": ssh_key,
                    },
                )
            )
        return [*lines, ""]

    def vyos(self) -> List[str]:
        lines = ["", "set service ssh disable-password-authentication"]
        for ssh_key in self.ctx.global_meta.get("ssh_keys", []):
            key_type, key, name = ssh_key.split(" ")[:3]
            lines.append(
                "set system login user supertech authentication"
                f" public-keys {name} key {key}"
            )
            lines.append(
                "set system login user supertech authentication"
                f" public-keys {name} type {key_type}"
            )
        return [*lines, ""]


class VyosPlatform(ConfigBlock):
    """VyOS platform services: update-check, SSH, BFD, HTTPS API, ping."""

    def vyos(self) -> List[str]:
        return [
            "set system update-check url https://raw.githubusercontent.com/vyos/"
            "vyos-nightly-build/refs/heads/rolling/version.json",
            "set service ssh port 22",
            "set protocols bfd profile bgp echo-mode",
            "set protocols bfd profile bgp interval echo-interval 50",
            "set service https api rest",
            "set service https api keys id vaultadmin key"
            f" '{secret_value(self.ctx.secrets, 'vyos_api_password')}'",
            "",
            "set firewall global-options all-ping enable",
            "set firewall global-options broadcast-ping enable",
            "",
        ]


class NtpConfig(ConfigBlock):
    """Fleet NTP sync (plus internal-only allow-client where serving).

    RouterOS owns only the client sync (the ``/system/ntp/client``
    singleton); serving LAN clients (``/system/ntp/server``) stays
    unmodeled.
    """

    SERVERS = ["time1.vyos.net", "time2.vyos.net", "time3.vyos.net"]
    ALLOW_CLIENTS = [
        "10.0.0.0/8",
        "127.0.0.0/8",
        "169.254.0.0/16",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "::1/128",
        "fc00::/7",
        "fe80::/10",
    ]

    def mikrotik(self) -> List[str]:
        return [
            ros_line(
                "/system/ntp/client",
                "set",
                {
                    "enabled": "yes",
                    "mode": "unicast",
                    "servers": ",".join(self.SERVERS),
                },
            ),
            "",
        ]

    def vyos(self) -> List[str]:
        # The allow-client syntax is chrony-era VyOS, not shared
        # vyatta lineage.
        return [
            *(f"set service ntp server {server}" for server in self.SERVERS),
            *(
                f"set service ntp allow-client address {net}"
                for net in self.ALLOW_CLIENTS
            ),
            "",
        ]


class ExtraConfig(ConfigBlock):
    """Verbatim extra_config lines (the all_suffix.j2 include).

    Carries the template's final unconditional blank separator, so it
    emits even when extra_config is empty.
    """

    def mikrotik(self) -> List[str]:
        return ["", *self.host.extra_config]

    def vyos(self) -> List[str]:
        return ["", *self.host.extra_config]

    def linux(self) -> List[str]:
        return ["", *self.host.extra_config]
