"""System/platform blocks: identity, services, access, extra config.

Each vendor method is a faithful translation of its template stanza
and must stay byte-identical to it (tests/golden/). Blank separator
lines are part of the contract: the templates emit them
unconditionally between sections, so blocks emit their own trailing
separators exactly where the template put them.
"""

from typing import List

from barf.configs.base import ConfigBlock, secret_value


class MikrotikHeader(ConfigBlock):
    """The RouterOS file header comment (mikrotik-only boilerplate)."""

    def mikrotik(self) -> List[str]:
        return [
            f"# {self.host.hostname} - generated by barf. RouterOS v7 CLI.",
            "# Sections mirror the fabric contract the VyOS/linux hosts implement:",
            "# WireGuard links, link addresses, eBGP to every spine, announced",
            "# networks, and geographic path weighting (origin-site large",
            "# communities in, local-pref out) when the host has a `site`.",
        ]


class VyosSystem(ConfigBlock):
    """VyOS system basics: identity, SNMP, DNS, syslog, conntrack."""

    def vyos(self) -> List[str]:
        gm = self.ctx.global_meta
        lines = [
            f"set system host-name '{self.host.hostname}'",
            f"set system domain-name '{gm.get('search_domain', '')}'",
            "set system login user supertech authentication"
            f" plaintext-password '{self.host.admin_password}'",
            f"set service snmp community '{gm.get('snmp_public', '')}'"
            " authorization 'ro'",
        ]
        location = self.host.snmp_location or gm.get("snmp_location", "")
        if location:
            lines.append(f"set service snmp location '{location}'")
        lines.append(f"set service snmp contact '{gm.get('snmp_contact', '')}'")
        for dns_server in self.host.nameservers:
            lines.append(f"set system name-server '{dns_server}'")
        lines += [
            "",
            # The factory-default empty loopback node; rendering it
            # keeps the owned diff clean instead of fighting the
            # default on every image.
            "set interfaces loopback lo",
            "",
            "set system syslog local facility all level info",
            "set system syslog local facility local7 level debug",
            "set system console device ttyS0 speed 115200",
            "set system config-management commit-revisions 100",
            "",
        ]
        # Conntrack helpers: the vyatta-era defaults, set explicitly.
        for module in ["ftp", "h323", "nfs", "pptp", "sip", "sqlnet", "tftp"]:
            lines.append(f"set system conntrack modules {module}")
        return lines


class VyosSshAccess(ConfigBlock):
    """Key-only SSH for the supertech account."""

    def vyos(self) -> List[str]:
        lines = ["", "set service ssh disable-password-authentication"]
        for ssh_key in self.ctx.global_meta.get("ssh_keys", []):
            key_type, key, name = ssh_key.split(" ")[:3]
            lines.append(
                "set system login user supertech authentication"
                f" public-keys {name} key {key}"
            )
            lines.append(
                "set system login user supertech authentication"
                f" public-keys {name} type {key_type}"
            )
        return [*lines, ""]


class VyosPlatform(ConfigBlock):
    """VyOS platform services: update-check, SSH, BFD, HTTPS API, ping."""

    def vyos(self) -> List[str]:
        return [
            "set system update-check url https://raw.githubusercontent.com/vyos/"
            "vyos-nightly-build/refs/heads/rolling/version.json",
            "set service ssh port 22",
            "set protocols bfd profile bgp echo-mode",
            "set protocols bfd profile bgp interval echo-interval 50",
            "set service https api rest",
            "set service https api keys id vaultadmin key"
            f" '{secret_value(self.ctx.secrets, 'vyos_api_password')}'",
            "",
            "set firewall global-options all-ping enable",
            "set firewall global-options broadcast-ping enable",
            "",
        ]


class VyosNtp(ConfigBlock):
    """NTP servers + internal-only allow-client (chrony-era syntax)."""

    ALLOW_CLIENTS = [
        "10.0.0.0/8",
        "127.0.0.0/8",
        "169.254.0.0/16",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "::1/128",
        "fc00::/7",
        "fe80::/10",
    ]

    def vyos(self) -> List[str]:
        return [
            "set service ntp server time1.vyos.net",
            "set service ntp server time2.vyos.net",
            "set service ntp server time3.vyos.net",
            *(
                f"set service ntp allow-client address {net}"
                for net in self.ALLOW_CLIENTS
            ),
            "",
        ]


class ExtraConfig(ConfigBlock):
    """Verbatim extra_config lines (the all_suffix.j2 include).

    Carries the template's final unconditional blank separator, so it
    emits even when extra_config is empty.
    """

    def mikrotik(self) -> List[str]:
        return ["", *self.host.extra_config]

    def vyos(self) -> List[str]:
        return ["", *self.host.extra_config]
