"""The vpn-role feature blocks.

Each class renders one feature; each vendor method is a faithful
translation of the corresponding template stanza and must stay
byte-identical to it (tests/golden/). Blank separator lines are part
of the contract: the templates emit them unconditionally between
sections (even when a section is empty), so blocks emit their own
trailing separators exactly where the template put them.
"""

from typing import TYPE_CHECKING, List

from barf.configs.base import ConfigBlock
from barf.configs.lines import ros_kv, ros_line
from barf.util.sites import SITE_ORIGIN_FUNC

if TYPE_CHECKING:
    from barf.model.wireguard import WGNetworkLink
    from barf.vendors import BaseHost

# The fabric's numbered-link /31 pool (transit export policy).
FABRIC_LINK_NET = "172.31.255.0/24"


def link_sides(link: "WGNetworkLink", device: "BaseHost"):
    """(our_side, other_peer) for a link touching ``device``."""
    if link.side_a == device:
        return link.side_a, link.side_b
    return link.side_b, link.side_a


def transit_of(host: "BaseHost") -> List[dict]:
    """The host's modeled transit ASes (bgp.transit), if any."""
    return host.bgp.get("transit", [])


def announced_networks(host: "BaseHost") -> List[str]:
    """Own networks plus modeled transit link networks.

    Transit link nets are announced (and tagged) like our own networks
    so every fabric session, adopted or new, advertises identically.
    """
    return host.networks + [t["link_network"] for t in transit_of(host)]


class MikrotikHeader(ConfigBlock):
    """The RouterOS file header comment (mikrotik-only boilerplate)."""

    def mikrotik(self) -> List[str]:
        return [
            f"# {self.host.hostname} - generated by barf. RouterOS v7 CLI.",
            "# Sections mirror the fabric contract the VyOS/linux hosts implement:",
            "# WireGuard links, link addresses, eBGP to every spine, announced",
            "# networks, and geographic path weighting (origin-site large",
            "# communities in, local-pref out) when the host has a `site`.",
        ]


class FabricWireGuard(ConfigBlock):
    """The Vault-derived fabric mesh links: WG interfaces + addressing.

    Unnumbered links (RFC 5549) get ND instead of an address: RAs teach
    us the peer's link-local (prefix=none answers without any global
    address; ND multicast rides the tunnel because allowed-address
    covers ::/0 -- live-verified on 7.22.3). /ipv6/nd entries silently
    discard comment= (accepted, never stored), so none is rendered: it
    would read as a forever-pending diff.
    """

    def mikrotik(self) -> List[str]:
        lines = []
        for link in self.ctx.vpn_links:
            interface_name = f"wg{link.link_id}"
            our_side, other_peer = link_sides(link, self.host)

            lines.append(
                ros_line(
                    "/interface/wireguard",
                    "add",
                    ros_kv("name", interface_name),
                    ros_kv("listen-port", link.link_id),
                    ros_kv("mtu", 1420),
                    ros_kv("private-key", link.wg_privkey(our_side), quote=True),
                    ros_kv(
                        "comment",
                        f"barf: {link.side_a.hostname} -> {link.side_b.hostname}",
                        quote=True,
                    ),
                )
            )
            peer = ros_line(
                "/interface/wireguard/peers",
                "add",
                ros_kv("interface", interface_name),
                ros_kv("name", other_peer.hostname),
                ros_kv("public-key", link.wg_pubkey(other_peer), quote=True),
                ros_kv("allowed-address", "0.0.0.0/0,::/0"),
            )
            if other_peer.wg_endpoint:
                peer += (
                    f" endpoint-address={other_peer.wg_endpoint}"
                    f" endpoint-port={link.link_id} persistent-keepalive=10s"
                )
            lines.append(peer)

            if link.unnumbered:
                lines.append(
                    f"/ipv6/nd add interface={interface_name} ra-interval=10s-15s"
                )
                lines.append(
                    "/ipv6/nd/prefix add prefix=none"
                    f" interface={interface_name}"
                    f' comment="barf: {other_peer.hostname} unnumbered BGP"'
                )
            else:
                lines.append(
                    f"/ip/address add address={link.get_ip(our_side, with_netmask=True)}"
                    f" interface={interface_name}"
                    f' comment="barf: {other_peer.hostname} link"'
                )
        return [*lines, ""]


class Bridges(ConfigBlock):
    """LAN/L2 bridges modeled in network.yml (vendor-neutral type=bridge).

    barf owns the bridge by name, its L3 addresses, and its member
    ports, so every member of an owned bridge must be modeled or it
    would be removed. The optional ``ra`` block is a real prefix RA for
    attached hosts, distinct from the fabric links' unnumbered RA.
    """

    def mikrotik(self) -> List[str]:
        lines = []
        for iface in self.host.interfaces:
            if not iface.is_bridge:
                continue
            add = f"/interface/bridge add name={iface.name}"
            if iface.description:
                add += f' comment="barf: {iface.description}"'
            lines.append(add)
            for member in iface.members:
                lines.append(
                    f"/interface/bridge/port add bridge={iface.name} interface={member}"
                )
            for addr in iface.addresses:
                lines.append(
                    f"/ip/address add address={addr.with_prefixlen}"
                    f" interface={iface.name}"
                    f' comment="barf: {iface.name} address"'
                )
            if iface.ra:
                nd = f"/ipv6/nd add interface={iface.name}"
                if iface.ra.get("hop_limit"):
                    nd += f" hop-limit={iface.ra['hop_limit']}"
                nd += (
                    f" advertise-dns={'yes' if iface.ra.get('advertise_dns') else 'no'}"
                )
                lines.append(nd)
        return [*lines, ""]


class StaticWireGuard(ConfigBlock):
    """Static WireGuard tunnels (vendor-neutral ``wireguard`` block).

    External peerings, not the Vault-derived fabric mesh: the peer
    key/endpoint are static and our private key is captured into Vault
    off the device, so the interface adopts byte-identical without a
    rekey.
    """

    def mikrotik(self) -> List[str]:
        lines = []
        for iface in self.host.interfaces:
            if not (iface.is_wireguard and iface.wireguard):
                continue
            wg = iface.wireguard
            lines.append(
                ros_line(
                    "/interface/wireguard",
                    "add",
                    ros_kv("name", iface.name),
                    ros_kv("listen-port", wg["port"]),
                    ros_kv("mtu", iface.mtu or 1420),
                    ros_kv(
                        "private-key",
                        self.host.secret(wg["private_key_secret"]),
                        quote=True,
                    ),
                    ros_kv("comment", f"barf: {iface.name} tunnel", quote=True),
                )
            )
            for peer in wg.get("peers", []):
                line = ros_line(
                    "/interface/wireguard/peers",
                    "add",
                    ros_kv("interface", iface.name),
                    ros_kv("name", peer["name"]),
                    ros_kv("public-key", peer["public_key"], quote=True),
                    ros_kv(
                        "allowed-address",
                        ",".join(peer.get("allowed_ips", ["0.0.0.0/0", "::/0"])),
                    ),
                )
                if peer.get("endpoint"):
                    line += (
                        f" endpoint-address={peer['endpoint']}"
                        f" endpoint-port={peer.get('port', wg['port'])}"
                        f" persistent-keepalive={peer.get('keepalive', '10s')}"
                    )
                lines.append(line)
            for addr in iface.addresses:
                lines.append(
                    f"/ip/address add address={addr.with_prefixlen}"
                    f" interface={iface.name}"
                    f' comment="barf: {iface.name} address"'
                )
        return [*lines, ""]


class AnnouncedNetworks(ConfigBlock):
    """The genprog-networks address-list backing BGP origination.

    Transit ASes are reflected into the fabric; their connected link
    nets are announced (and tagged) like our own networks so every
    fabric session, adopted or new, advertises identically.
    """

    def mikrotik(self) -> List[str]:
        return [
            *(
                f"/ip/firewall/address-list add list=genprog-networks"
                f' address={network} comment="barf: announced to the fabric"'
                for network in announced_networks(self.host)
            ),
            "",
        ]


class FirewallGroups(ConfigBlock):
    """Vendor-neutral firewall groups (barf/util/firewall.py).

    Address members split by family into the v4/v6 address-list trees;
    interface lists render their nesting via include=.
    """

    def mikrotik(self) -> List[str]:
        lines = []
        for group in self.host.firewall.address:
            for version, path in ((4, "/ip"), (6, "/ipv6")):
                for member in group.members_v(version):
                    line = (
                        f"{path}/firewall/address-list add list={group.name}"
                        f" address={member.address}"
                    )
                    if member.comment:
                        line += f' comment="{member.comment}"'
                    lines.append(line)
        for group in self.host.firewall.interface:
            add = f"/interface/list add name={group.name}"
            if group.include:
                add += f" include={','.join(group.include)}"
            lines.append(add)
            for iface in group.interfaces:
                lines.append(
                    f"/interface/list/member add list={group.name} interface={iface}"
                )
        return [*lines, ""]


class SiteWeighting(ConfigBlock):
    """Geographic path weighting filters (origin-site tag out, pref in).

    Tags carry the fabric-wide community_asn (RFC 8195 Global
    Administrator), never the per-host ASN -- see barf/util/sites.py
    for the distance math; only the ready-made integers render here.
    With transit modeled the export chain ends in an explicit reject
    (this host does not re-export fabric routes between fabric peers);
    without transit it stays accept-all like the rest of the fleet.

    The section is gated on origin_site but its trailing separator is
    not (the template's blank line renders unconditionally), so
    applies() stays True and an unweighted host emits just the blank.
    """

    def mikrotik(self) -> List[str]:
        if not self.ctx.origin_site:
            return [""]

        asn = self.ctx.community_asn
        transit = transit_of(self.host)
        lines = []
        for network in announced_networks(self.host):
            lines.append(
                "/routing/filter/rule add chain=genprog-out"
                ' comment="barf: origin-site tag"'
                f' rule="if (dst == {network}) {{ set bgp-large-communities'
                f' {asn}:{SITE_ORIGIN_FUNC}:{self.ctx.origin_site.id}; accept }}"'
            )
        for t in transit:
            lines.append(
                "/routing/filter/rule add chain=genprog-out"
                f' comment="barf: reflect {t["name"]} (AS {t["remote_as"]}) into'
                ' the fabric"'
                f' rule="if (dst-len != 0 && bgp-input-remote-as =='
                f' {t["remote_as"]}) {{ accept }}"'
            )
        if transit:
            lines.append(
                "/routing/filter/rule add chain=genprog-out"
                ' comment="barf: no other re-export" rule="reject"'
            )
        else:
            lines.append('/routing/filter/rule add chain=genprog-out rule="accept"')
        for site_name, rules in self.ctx.site_import_rules.items():
            for rule in rules:
                lines.append(
                    f"/routing/filter/rule add chain=genprog-in-{site_name}"
                    f' comment="barf: origin site {rule.site_id}"'
                    f' rule="if (bgp-large-communities includes'
                    f" {asn}:{SITE_ORIGIN_FUNC}:{rule.site_id})"
                    f' {{ set bgp-local-pref {rule.local_pref}; accept }}"'
                )
            lines.append(
                f"/routing/filter/rule add chain=genprog-in-{site_name}"
                ' comment="barf: untagged fallthrough" rule="accept"'
            )
        return [*lines, ""]


class FabricBGP(ConfigBlock):
    """The fabric BGP template and one connection per mesh link.

    Unnumbered connections: local.address is the INTERFACE, no
    remote.address (the peer's link-local is discovered via ND), and
    afi=ip,ipv6 is mandatory -- the default afi=ip establishes but
    exchanges zero prefixes (live-learned). IPv4 NLRIs then ride IPv6
    next-hops via the extended-nexthop capability.
    """

    def mikrotik(self) -> List[str]:
        template = (
            f"/routing/bgp/template add name=genprog-fabric as={self.host.asn}"
            " hold-time=30s keepalive-time=10s"
        )
        if announced_networks(self.host):
            template += " output.network=genprog-networks"
        lines = [template]

        for link in self.ctx.vpn_links:
            interface_name = f"wg{link.link_id}"
            our_side, other_peer = link_sides(link, self.host)
            weighted = self.ctx.site_import_rules.get(other_peer.site)
            instance = (
                f" instance={self.host.bgp['instance']}"
                if self.host.bgp.get("instance")
                else ""
            )
            policy = (
                f" input.filter=genprog-in-{other_peer.site}" if weighted else ""
            ) + (" output.filter-chain=genprog-out" if self.ctx.origin_site else "")

            if link.unnumbered:
                lines.append(
                    f"/routing/bgp/connection add name={other_peer.hostname}"
                    f" templates=genprog-fabric{instance}"
                    f" local.address={interface_name} local.role=ebgp"
                    f" remote.as={other_peer.asn} afi=ip,ipv6{policy}"
                    f' comment="barf: {other_peer.hostname}"'
                )
            else:
                lines.append(
                    f"/routing/bgp/connection add name={other_peer.hostname}"
                    f" templates=genprog-fabric{instance}"
                    f" remote.address={link.get_ip(other_peer)}"
                    f" remote.as={other_peer.asn}"
                    f" local.address={link.get_ip(our_side)} local.role=ebgp{policy}"
                    f' comment="barf: {other_peer.hostname}"'
                )
        return [*lines, ""]


class TransitBGP(ConfigBlock):
    """Transit BGP sessions barf owns (the retired hand `export` chain).

    genprog-out-transit reproduces that chain's toward-transit rules
    verbatim from the model (the toward-fabric direction is handled by
    genprog-out); the session rides genprog-transit, a template shaped
    like the hand `default` (an AS, no output.network -- origination
    stays connected-matched).
    """

    def applies(self) -> bool:
        return bool(transit_of(self.host))

    def mikrotik(self) -> List[str]:
        transit = transit_of(self.host)
        lines = []
        for t in transit:
            name, remote_as = t["name"], t["remote_as"]
            lines.extend(
                [
                    "/routing/filter/rule add chain=genprog-out-transit"
                    f' comment="barf: export fabric routes to {name} (AS {remote_as})"'
                    f' rule="if (dst-len != 0 && bgp-output-remote-as == {remote_as}'
                    f' && bgp-input-remote-as != {remote_as}) {{accept}}"',
                    "/routing/filter/rule add chain=genprog-out-transit"
                    f' comment="barf: reflect {name} routes to the fabric"'
                    f' rule="if (dst-len != 0 && bgp-output-remote-as != {remote_as}'
                    f' && bgp-input-remote-as == {remote_as}) {{accept}}"',
                    "/routing/filter/rule add chain=genprog-out-transit"
                    f' comment="barf: export {name} link prefix to the fabric"'
                    f' rule="if (dst-len != 0 && protocol connected && dst in'
                    f" {t['export_supernet']} && bgp-output-remote-as !="
                    f' {remote_as}) {{accept}}"',
                    "/routing/filter/rule add chain=genprog-out-transit"
                    f' comment="barf: export fabric link prefixes to {name}"'
                    f' rule="if (dst-len != 0 && protocol connected && dst in'
                    f" {FABRIC_LINK_NET} && bgp-output-remote-as =="
                    f' {remote_as}) {{accept}}"',
                ]
            )
        internal = " or ".join(f"dst in {net}" for net in self.host.networks)
        lines.append(
            "/routing/filter/rule add chain=genprog-out-transit"
            ' comment="barf: announce internal prefixes, drop other connected"'
            f' rule="if (protocol connected && ({internal})) {{accept}} else'
            ' {reject}"'
        )
        lines.append("")
        lines.append(
            f"/routing/bgp/template add name=genprog-transit as={self.host.asn}"
            " routing-table=main"
        )
        for t in transit:
            instance = (
                f" instance={self.host.bgp['instance']}"
                if self.host.bgp.get("instance")
                else ""
            )
            lines.append(
                f"/routing/bgp/connection add name={t['name']}"
                f" templates=genprog-transit{instance}"
                f" remote.address={t['remote_address']} remote.as={t['remote_as']}"
                " local.role=ebgp output.filter-chain=genprog-out-transit"
                f' comment="barf: {t["name"]} transit"'
            )
        return lines


class ExtraConfig(ConfigBlock):
    """Verbatim extra_config lines (the all_suffix.j2 include).

    Carries the template's final unconditional blank separator, so it
    emits even when extra_config is empty.
    """

    def mikrotik(self) -> List[str]:
        return ["", *self.host.extra_config]
