version: "3.6"
services:
  grafana:
    image: grafana/grafana:master
    environment:
      GF_SERVER_ROOT_URL: https://grafana.generalprogramming.org
    env_file: .env_grafana
    volumes:
      - /srv/grafana/data:/var/lib/grafana
      - /srv/grafana/log:/var/log/grafana
      - /srv/grafana/etc:/etc/grafana
    networks:
      - logging
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=3000
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:grafana.generalprogramming.org
      restart_policy:
        condition: any

  kibana:
    build: kibana
    image: registry.generalprogramming.org/kibana
    environment:
      SERVER_NAME: logs.generalprogramming.org
      ELASTICSEARCH_HOSTS: http://192.168.3.2:9200
      XPACK_MONITORING_ENABLED: "true"
      XPACK_INFRA_SOURCES_DEFAULT_LOGALIAS: "logstash-*"
      XPACK_INFRA_SOURCES_DEFAULT_FIELDS_HOST: "host"
    networks:
      - logging
      - publicweb
    deploy:
      restart_policy:
        condition: any

  kibana-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    command:
      - --provider=oidc
      - --provider-display-name=FreeIPA
      - --oidc-issuer-url=https://auth.generalprogramming.org
      - --cookie-secure=false
      - --upstream=http://kibana:5601
      - --http-address=http://0.0.0.0:5601
      - --redirect-url=https://logs.generalprogramming.org/oauth2/callback
      - --email-domain=*
    environment:
      OAUTH2_PROXY_COOKIE_DOMAIN: logs.generalprogramming.org
    env_file: .env_oauth
    networks:
      - logging
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=5601
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:logs.generalprogramming.org
      restart_policy:
        condition: any

  prometheus:
    build: prometheus
    image: registry.generalprogramming.org/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.max-block-duration=2h --storage.tsdb.min-block-duration=2h --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles --web.enable-lifecycle
    volumes:
      - /srv/var/prometheus:/prometheus
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  prometheus-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    command:
      - --provider=oidc
      - --provider-display-name=FreeIPA
      - --oidc-issuer-url=https://auth.generalprogramming.org
      - --cookie-secure=false
      - --upstream=http://thanos-query:9090
      - --http-address=http://0.0.0.0:5601
      - --redirect-url=https://prometheus.generalprogramming.org/oauth2/callback
      - --email-domain=*
    environment:
      OAUTH2_PROXY_COOKIE_DOMAIN: prometheus.generalprogramming.org
    env_file: .env_oauth
    networks:
      - logging
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=5601
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:prometheus.generalprogramming.org
      restart_policy:
        condition: any

  thanosminio:
    image: minio/minio
    command: server /data
    volumes:
      - /srv/var/thanos/minio:/data
    environment:
      MINIO_ACCESS_KEY: THANOS_ACCESS_INTERNAL
      MINIO_SECRET_KEY: THANOS_INSECURE_SECRET
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  thanos-sidecar:
    image: thanosio/thanos:v0.14.0
    command: "sidecar --prometheus.url=http://prometheus:9090 --tsdb.path=/prometheus --objstore.config-file=/thanos/bucket_config.yml --shipper.upload-compacted"
    volumes:
      - /srv/var/thanos/bucket_config.yml:/thanos/bucket_config.yml:ro
      - /srv/var/prometheus:/prometheus
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  thanos-store:
    image: thanosio/thanos:v0.14.0
    command: 'store --data-dir "/thanos/store" --objstore.config-file=/thanos/bucket_config.yml'
    volumes:
      - /srv/var/thanos/store:/thanos/store
      - /srv/var/thanos/bucket_config.yml:/thanos/bucket_config.yml:ro
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  thanos-query:
    image: thanosio/thanos:v0.14.0
    command: 'query --http-address "0.0.0.0:9090" --query.replica-label "replica" --store thanos-sidecar:10901 --store thanos-store:10901'
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  thanos-compactor:
    image: thanosio/thanos:v0.14.0
    command: 'compact --wait --data-dir "/thanos/store" --objstore.config-file=/thanos/bucket_config.yml'
    networks:
      - logging
    volumes:
      - /srv/var/thanos/store:/thanos/store
      - /srv/var/thanos/bucket_config.yml:/thanos/bucket_config.yml:ro
    deploy:
      restart_policy:
        condition: any
      

networks:
  logging:
    driver: overlay
  publicweb:
    driver: overlay
    external: true
