version: "3.6"
services:
  grafana:
    image: grafana/grafana:main
    environment:
      GF_SERVER_ROOT_URL: https://grafana.generalprogramming.org
    env_file: .env_grafana
    volumes:
      - /srv/grafana/data:/var/lib/grafana
      - /srv/grafana/log:/var/log/grafana
      - /srv/grafana/etc:/etc/grafana
    networks:
      - logging
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=3000
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:grafana.generalprogramming.org
        # Traefik 2
        - traefik.http.routers.grafana.rule=Host(`grafana.generalprogramming.org`)
        - traefik.http.services.grafana.loadbalancer.server.port=3000
      restart_policy:
        condition: any

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.max-block-duration=2h --storage.tsdb.min-block-duration=2h --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles --web.enable-lifecycle
    volumes:
      - /srv/etc/prometheus:/etc/prometheus
      - /srv/var/prometheus:/prometheus
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  alertmanager:
    image: prom/alertmanager:main
    command: --config.file=/alertmanager/config.yml --storage.path="/data"
    volumes:
      - /srv/etc/alertmanager:/alertmanager
      - /srv/var/alertmanager:/data
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  prometheus-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    command:
      - --provider=oidc
      - --custom-sign-in-logo=https://cdn.owo.me/file/nepeat-public/genprog/logo-transparent-dark.png
      - --provider-display-name=General Programming
      - --oidc-issuer-url=https://auth.generalprogramming.org
      - --cookie-secure=false
      - --upstream=http://thanos-query:9090
      - --http-address=http://0.0.0.0:5601
      - --redirect-url=https://prometheus.generalprogramming.org/oauth2/callback
      - --email-domain=*
      - --custom-templates-dir=/templates
    volumes:
      - /srv/share/oauth2_proxy_templates:/templates:ro
    environment:
      OAUTH2_PROXY_COOKIE_DOMAIN: prometheus.generalprogramming.org
    env_file: .env_oauth
    networks:
      - logging
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=5601
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:prometheus.generalprogramming.org
        # Traefik 2
        - traefik.http.routers.prometheus_proxy.rule=Host(`prometheus.generalprogramming.org`)
        - traefik.http.services.prometheus_proxy.loadbalancer.server.port=5601
      restart_policy:
        condition: any

  thanos-redis:
    image: redis:alpine
    volumes:
      - /srv/var/thanos/redis:/data
    networks:
      - logging

  thanos-memcache:
    image: memcached:alpine
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  thanos-sidecar:
    image: thanosio/thanos:v0.31.0
    command: "sidecar --prometheus.url=http://prometheus:9090 --tsdb.path=/prometheus --objstore.config-file=/thanos/bucket_config.yml --shipper.upload-compacted"
    volumes:
      - /srv/var/thanos/bucket_config.yml:/thanos/bucket_config.yml:ro
      - /srv/var/prometheus:/prometheus
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  thanos-store:
    image: thanosio/thanos:v0.31.0
    command: 'store --data-dir "/thanos/store" --objstore.config-file=/thanos/bucket_config.yml --index-cache.config-file=/thanos/thanos_cache.yml --store.caching-bucket.config-file=/thanos/thanos_cache.yml'
    volumes:
      - /srv/var/thanos/store:/thanos/store
      - /srv/var/thanos/bucket_config.yml:/thanos/bucket_config.yml:ro
      - /srv/var/thanos/thanos_cache.yml:/thanos/thanos_cache.yml:ro
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  thanos-query-backend:
    image: thanosio/thanos:v0.31.0
    command: 'query --http-address "0.0.0.0:9090" --query.replica-label "replica" --store thanos-sidecar:10901 --store thanos-store:10901'
    networks:
      - logging
    deploy:
      restart_policy:
        condition: any

  thanos-query:
    image: thanosio/thanos:v0.31.0
    command: 'query-frontend --http-address "0.0.0.0:9090" --query-range.response-cache-config-file=/thanos/thanos_cache.yml --labels.response-cache-config-file=/thanos/thanos_cache.yml --query-frontend.downstream-url="http://thanos-query-backend:9090"'
    networks:
      - logging
    volumes:
      - /srv/var/thanos/thanos_cache.yml:/thanos/thanos_cache.yml:ro
    deploy:
      restart_policy:
        condition: any

  thanos-compactor:
    image: thanosio/thanos:v0.31.0
    command: 'compact --wait --data-dir "/thanos/store" --objstore.config-file=/thanos/bucket_config.yml'
    networks:
      - logging
    volumes:
      - /srv/var/thanos/store:/thanos/store
      - /srv/var/thanos/bucket_config.yml:/thanos/bucket_config.yml:ro
    deploy:
      restart_policy:
        condition: any

networks:
  logging:
    driver: overlay
  publicweb:
    driver: overlay
    external: true
