// Generated by Wrangler on Sat Aug 03 2024 22:48:52 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	DISCORD_PUB_KEY: "8fea7e6bebcc5b78ae79bc6520d2127b2468440d2fa839c338e74914ca642f9b";
	TWILIO_CONFIG: DurableObjectNamespace<import("./src/index").TwilioConfig>;
}
