version: "3.6"
services:
  redis:
    image: redis:alpine
    env_file: .env
    command: 'redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru --save ""'
    networks:
      - kolide
    deploy:
      restart_policy:
        condition: any

  kolide:
    image: kolide/fleet:latest
    environment:
      KOLIDE_SERVER_TLS: "false"
      KOLIDE_REDIS_ADDRESS: redis
    env_file: .env
    command: /usr/bin/fleet serve
    networks:
      - publicweb
      - kolide
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:kolide.generalprogramming.org
      restart_policy:
        condition: any

  kolide_service:
    image: kolide/fleet:latest
    environment:
      KOLIDE_SERVER_TLS: "false"
      KOLIDE_REDIS_ADDRESS: redis
    env_file: .env
    command: 'sh -c "tail -f /dev/null"'
    networks:
      - publicweb
      - kolide

networks:
  publicweb:
    driver: overlay
    external: true
  kolide:
    driver: overlay
