apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cidr-groups.yaml
  - flow-collector.yaml
  - scrape-cilium.yaml
  - ccnp-deny-metadata.yaml
  - ccnp-deny-node-api.yaml
  - ccnp-deny-storage-plane.yaml
