apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-gateway
  namespace: loki
  annotations:
    tailscale.com/hostname: "loki-fmt2"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: loki-gateway
      port:
        number: 80
  tls:
    - hosts:
        - loki-fmt2
