version: '3.6'

services:
  consul:
    image: hashicorp/consul:1.20.2
    deploy:
      restart_policy:
        condition: any
      mode: global
    networks:
      - hostnet
    volumes:
      - /var/lib/consul:/consul/data
      - /etc/consul:/consul/config
    command: consul agent -config-dir /consul/config
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS: ''

networks:
  hostnet:
    external: true
    name: host
