# Production Compose
version: "3.6"
services:
  redis:
    image: redis:alpine
    networks:
      - bankwatch
    volumes:
      - /srv/bankwatch/redis:/data
    deploy:
      restart_policy:
        condition: any

  webhooks:
    build: .
    image: registry.nepeat.com/bankwatch
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file: .env
    command: gunicorn -b 0.0.0.0:5000 -k gevent -w 4 api:app
    networks:
      - bankwatch
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=5000
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:bankwatch.api.nepeat.com
      restart_policy:
        condition: any

networks:
  bankwatch:
    driver: overlay
  publicweb:
    driver: overlay
    external: true
