apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-attic-secrets
  namespace: attic
spec:
  type: kv-v2
  mount: secret
  path: app/attic-secrets
  destination:
    name: attic-secrets
    create: true
  refreshAfter: 30s
