
defaultVaultConnection:
  enabled: true
  address: 'https://10.65.67.27:8200'
  # cert SAN is the DNS name; pin it since we dial the LAN IP
  tlsServerName: vault-proxy.catgirls.dev

defaultAuthMethod:
  enabled: true
  namespace: vault
  kubernetes:
    role: k8s-read
  mount: "kubernetes-sea1"
