version: '2'
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    restart: always
    command:
      - "-retentionPeriod=12"
      - "-usePromCompatibleNaming"
    volumes:
      - /var/lib/victoria-metrics-data:/victoria-metrics-data
    env_file:
      - .env
    ports:
      - "$PRIVATE_IP:8428:8428"
