version: "3.6"
services:
  staticweb:
    image: registry.nepeat.com/nginx-web:v3
    volumes:
      - /srv/www:/var/www
    networks:
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.docker.network=publicweb
        - traefik.backend=nginx
        # Routes
        - traefik.main.frontend.rule=Host:www.nepeat.com,nepeat.com
        # - traefik.soy.frontend.rule=Host:www.fucking.soy,fucking.soy
      restart_policy:
        condition: any

networks:
  publicweb:
    driver: overlay
    external: true
