# Production Compose
version: "3.6"
services:
  redis:
    image: redis:4.0.11-alpine
    command: 'redis-server --save 0'
    networks:
      - mailrenderapi
    deploy:
      restart_policy:
        condition: on-failure

  render:
    build: render_api
    image: registry.nepeat.com/mailapi_render
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file: .env
    command: python3 api.py
    networks:
      - mailrenderapi
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:mailrender.api.nepeat.com
      restart_policy:
        condition: on-failure

  webhooks:
    build: webhooks
    image: registry.nepeat.com/mailapi_webhooks
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    env_file: .env
    command: python3 api.py
    networks:
      - mailrenderapi
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:mailhooker.api.nepeat.com
      restart_policy:
        condition: on-failure

networks:
  mailrenderapi:
    driver: overlay
  publicweb:
    driver: overlay
    external: true