# Production Compose
version: "3.6"
services:
  webhooks:
    build: webhooks
    image: registry.generalprogramming.org/mailapi_webhooks
    env_file: .env
    command: python3 api.py
    networks:
      - mailrenderapi
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:mailhooker.api.generalprogramming.org
      restart_policy:
        condition: on-failure

networks:
  mailrenderapi:
    driver: overlay
  publicweb:
    driver: overlay
    external: true