---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clickhouse-operator
helmCharts:
  - name: altinity-clickhouse-operator
    releaseName: clickhouse-operator
    repo: https://helm.altinity.com
    version: 0.26.0
    namespace: clickhouse-operator
    valuesInline:
      configs:
        files:
          config.yaml:
            watch:
              namespaces: [""]
