---
- name: "etcd - Create folders"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "/opt/etcd/{{ etcd_version }}/bin"

- name: "etcd - Download"
  unarchive:
    src: "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: true

- name: "etcd - Install binaries"
  copy:
    src: "/tmp/etcd-{{ etcd_version }}-linux-amd64/{{ item }}"
    dest: "/opt/etcd/{{ etcd_version }}/bin/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: true
  with_items:
    - etcd
    - etcdctl

- name: "etcd - Link binaries"
  shell: "ln -svf /opt/etcd/{{ etcd_version }}/bin/* /usr/bin/"
  args:
    chdir: "/opt/etcd/{{ etcd_version }}/bin"

- name: "etcd - Create systemd config"
  template:
    src: "service-etcd.j2"
    dest: "/etc/systemd/system/etcd.service"
    owner: "root"
    group: "root"
    mode: "0664"
  register: etcd_config

- name: "etcd - Update systemd daemon configuration and restart daemon"
  systemd:
    name: etcd
    enabled: true
    state: restarted
    daemon_reload: yes
  when: etcd_config.changed
