---
- name: "K8S - Wait for cluster startup"
  pause:
    seconds: 5

- name: "K8S - Create addon folders"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/kubernetes/addons/dns

- name: "K8S - Addon manager - Upload"
  copy:
    src: "kube-addon-manager.yaml"
    dest: "/etc/kubernetes/manifests/kube-addon-manager.yaml"
    owner: "root"
    group: "root"
    mode: "755"

- name: "K8S - DNS - Service"
  template:
    src: "addon-kubedns-svc.j2"
    dest: "/etc/kubernetes/addons/dns/kubedns-svc.yaml"
    owner: "root"
    group: "root"
    mode: "755"

- name: "K8S - DNS - Controller"
  template:
    src: "addon-kubedns-controller.j2"
    dest: "/etc/kubernetes/addons/dns/kubedns-controller.yaml"
    owner: "root"
    group: "root"
    mode: "755"
  with_items:
    - "addon-kubedns-controller.j2"
    - "kubedns-sa.yaml"


- name: "K8S - DNS - Upload static"
  copy:
    src: "{{ item }}"
    dest: "/etc/kubernetes/addons/dns/"
    owner: "root"
    group: "root"
    mode: "755"
  with_items:
    - "kubedns-sa.yaml"
    - "kubedns-cm.yaml"
