---

- name: "K8S - Upload controller kubelet manifests"
  template:
    src: "manifest-controller.j2"
    dest: "/etc/kubernetes/manifests/controller.manifest"
    owner: "root"
    group: "root"
    mode: "0755"
  when: kube_master

- name: "K8S - Upload scheduler kubelet manifests"
  template:
    src: "manifest-scheduler.j2"
    dest: "/etc/kubernetes/manifests/scheduler.manifest"
    owner: "root"
    group: "root"
    mode: "0755"
  when: kube_master

- name: "K8S - Upload apiserver manifest"
  template:
    src: "manifest-apiserver.j2"
    dest: "/etc/kubernetes/manifests/apiserver.manifest"
    owner: "root"
    group: "root"
    mode: "0755"
  when: kube_master

- name: "K8S - Upload kubelet systemd service"
  template:
    src: "service-kubelet.j2"
    dest: "/etc/systemd/system/kubelet.service"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "K8S - Upload kubeproxy systemd service"
  template:
    src: "service-kubeproxy.j2"
    dest: "/etc/systemd/system/kube-proxy.service"
    owner: "root"
    group: "root"
    mode: "0755"
