# Production Compose
version: "3.6"
services:
  webhooks:
    build: .
    image: registry.generalprogramming.org/html_render_server
    env_file: .env
    command: python3 api.py
    networks:
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:htmlrender.generalprogramming.org
        # Traefik 2
        - traefik.http.routers.htmlrender.rule=Host(`htmlrender.generalprogramming.org`)
        - traefik.http.services.htmlrender.loadbalancer.server.port=8080
      restart_policy:
        condition: on-failure
networks:
  publicweb:
    driver: overlay
    external: true
