apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt-genprog
spec:
  secretName: tls-generalprogramming
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-genprog
  dnsNames:
    - "generalprogramming.org"
    - "*.generalprogramming.org"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt-catgirls
spec:
  secretName: tls-catgirls
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-genprog
  dnsNames:
    - "catgirls.dev"
    - "*.catgirls.dev"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt-owo
spec:
  secretName: tls-owo
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-genprog
  dnsNames:
    - "owo.me"
    - "*.owo.me"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt-e2pm
spec:
  secretName: tls-e2pm
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-genprog
  dnsNames:
    - "e2.pm"
    - "*.e2.pm"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt-coolmathgames
spec:
  secretName: tls-coolmathgames
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-genprog
  dnsNames:
    - "coolmathgam.es"
    - "*.coolmathgam.es"
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default

spec:
  certificates:
    - secretName: tls-generalprogramming
    - secretName: tls-catgirls
    - secretName: tls-owo
    - secretName: tls-e2pm
    - secretName: tls-coolmathgames
  defaultCertificate:
    secretName: tls-generalprogramming
