package vyosconfig

import (
	"encoding/json"
	"os"
	"slices"
	"testing"
)

// This file replays a corpus captured from the authoritative Python
// implementation (projects/barf/barf/util/vyos_config.py); testdata is
// regenerated by running those functions over the same inputs.
//
// The MinimalDeletePaths corpus is randomized (300 running/removed pairs
// over a 3-symbol alphabet, depth <= 4) because its output becomes
// `delete` ops against a live router: an off-by-one in the collapse rule
// silently deletes config that should survive.

type referenceCorpus struct {
	// MinDel entries are [running, removed, expected deletes].
	MinDel [][3][][]string `json:"mindel"`
}

func loadCorpus(t *testing.T) referenceCorpus {
	t.Helper()
	raw, err := os.ReadFile("testdata/python_reference.json")
	if err != nil {
		t.Fatalf("reading reference corpus: %v", err)
	}
	var corpus referenceCorpus
	if err := json.Unmarshal(raw, &corpus); err != nil {
		t.Fatalf("decoding reference corpus: %v", err)
	}
	return corpus
}

func TestReferenceMinimalDeletePaths(t *testing.T) {
	corpus := loadCorpus(t)
	if len(corpus.MinDel) < 100 {
		t.Fatalf("minimal-delete corpus too small: %d", len(corpus.MinDel))
	}
	for i, entry := range corpus.MinDel {
		running := NewSet(toPaths(entry[0])...)
		removed := toPaths(entry[1])
		want := toPaths(entry[2])

		got := MinimalDeletePaths(removed, running)
		if len(got) != len(want) {
			t.Fatalf("case %d: MinimalDeletePaths(%v, %v) = %v, python got %v",
				i, removed, entry[0], got, want)
		}
		for j := range got {
			if !slices.Equal(got[j], want[j]) {
				t.Fatalf("case %d: MinimalDeletePaths(%v, %v) = %v, python got %v",
					i, removed, entry[0], got, want)
			}
		}
	}
}

func toPaths(raw [][]string) []Path {
	out := make([]Path, 0, len(raw))
	for _, components := range raw {
		out = append(out, Path(components))
	}
	return out
}
