---
- name: "Generate holepunch command"
  ansible.builtin.set_fact:
    _holepunch_command: "curl -L -X POST '{{ holepunch_url }}' -H 'Content-Type: application/json' --data-raw '{\"key\": \"{{ holepunch_key }}\"}'"
  when: holepunch_key != "" and holepunch_url != ""

- name: "Run holepunch command"
  ansible.builtin.command: "{{ _holepunch_command }}"
  when: holepunch_key != "" and holepunch_url != ""

- name: "Add holepunch command to crontab"
  ansible.builtin.cron:
    name: "vault_holepunch"
    job: "{{ _holepunch_command }}"
    minute: "*/60"
    user: nobody
    state: present
  when: holepunch_key != "" and holepunch_url != ""

- name: "Verify if Consul is pingable."
  ansible.builtin.command:
    cmd: "ping -c 3 {{ consul_servers[0] }}"
  ignore_errors: true
  register: _consul_ping

- name: "Conenct via Netmaker if not pingable."
  ansible.builtin.command:
    cmd: "netclient join -vvvv -t {{ netmaker_token }}"
  when: _consul_ping.rc != 0 and netmaker_token != ""
