version: '3.6'

services:
  dex:
    image: dexidp/dex:v2.36.0-alpine
    volumes:
      - /etc/ipa/ca.crt:/ipa_ca.crt:ro
      - /srv/etc/dex.yaml:/config.yaml:ro
    networks:
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=5556
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:auth.generalprogramming.org
        # Traefik 2
        - traefik.http.routers.dex.rule=Host(`auth.generalprogramming.org`)
        - traefik.http.services.dex.loadbalancer.server.port=5556
      restart_policy:
        condition: any
    command: dex serve /config.yaml

networks:
  publicweb:
    driver: overlay
    external: true
