version: "3.6"
services:
  staticweb:
    build: .
    image: registry.nepeat.com/nginx-web
    volumes:
      - /srv/www:/var/www
    networks:
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.docker.network=publicweb
        - traefik.backend=nginx
        # Routes
        - traefik.main.frontend.rule=Host:www.nepeat.com,nepeat.com
        - traefik.portfolio.frontend.rule=Host:portfolio.nepeat.com
        - traefik.gaysounds.frontend.rule=Host:gaysounds.shitpos.ts.it
        - traefik.rpan.frontend.rule=Host:rpan.generalprogramming.org
        - traefik.erin_e2pm.frontend.rule=Host:www.e2.pm,e2.pm
        - traefik.googleboats.frontend.rule=Host:www.google.boats,google.boats
        - traefik.ewitch.frontend.rule=Host:www.e-wit.ch,e-wit.ch
      restart_policy:
        condition: any

networks:
  publicweb:
    driver: overlay
    external: true
