version: "3.6"
services:
  openvpn:
    image: kylemanna/openvpn
    volumes:
      - openvpn:/etc/openvpn
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    restart: on-failure
volumes:
  openvpn:
    external: true
