---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-coder
spec:
  type: kv-v2
  mount: secret
  path: app/coder
  destination:
    name: coder-secrets
    create: true
  refreshAfter: 1m
