package render

import (
	"fmt"
	"strings"

	"github.com/general-programming/megarepo/go/pkg/barf/model"
)

// fabricLinkNet is the fabric's numbered-link /31 pool (transit export
// policy).
const fabricLinkNet = "172.31.255.0/24"

// mikrotikSSHUser is where the fleet ssh_keys land: RouterOS has no
// supertech account.
const mikrotikSSHUser = "admin"

// MikroTik renders a RouterOS v7 CLI script.
//
// Port of the ("vpn", "mikrotik") entry of the Python BLOCK_REGISTRY.
type MikroTik struct{}

// Render returns the RouterOS config commands for h.
func (MikroTik) Render(h *model.Host, n *model.Network, s SecretSource) (string, error) {
	if h.Role != "vpn" {
		return "", fmt.Errorf("%s: only the vpn role is ported for mikrotik (got %q)",
			h.Hostname, h.Role)
	}
	ctx := newRenderCtx(h, n, s)

	// The RouterOS path has no IPsec branch: such a link would render as
	// WireGuard (generating spurious keypairs) and then vanish from the
	// diff via ownership scoping. Fail fast instead.
	for _, link := range ctx.links {
		if link.IPsec {
			return "", fmt.Errorf("%s: ipsec link to %s is not supported on mikrotik hosts",
				h.Hostname, link.Other(h.Hostname))
		}
	}

	blocks := []func(*renderCtx) ([]string, error){
		mikrotikHeader,
		mikrotikFabricWireGuard,
		mikrotikBridges,
		mikrotikStaticWireGuard,
		mikrotikAnnouncedNetworks,
		mikrotikFirewallGroups,
		mikrotikNTPConfig,
		mikrotikSSHConfig,
		mikrotikSiteWeighting,
		mikrotikFabricBGP,
		mikrotikTransitBGP,
		vyosExtraConfig, // configs.system.ExtraConfig is identical per vendor.
	}

	var lines []string
	for _, block := range blocks {
		emitted, err := block(ctx)
		if err != nil {
			return "", err
		}
		lines = append(lines, emitted...)
	}
	return strings.Join(lines, "\n") + "\n", nil
}

// -- line builders ----------------------------------------------------

// prop is one RouterOS property. A slice of these rather than a map:
// emission order is part of the output contract.
type prop struct {
	key   string
	value string
}

// rosValue quotes a RouterOS property value exactly when it needs it.
// Unquoted values with spaces silently break (the find-where gotcha), so
// anything containing whitespace, quotes, or backslashes -- or the empty
// string -- is double-quoted with RouterOS escaping.
func rosValue(value string) string {
	if value == "" || strings.ContainsAny(value, " \t\"\\") {
		escaped := strings.ReplaceAll(value, "\\", "\\\\")
		escaped = strings.ReplaceAll(escaped, "\"", "\\\"")
		return "\"" + escaped + "\""
	}
	return value
}

// rosLine builds one RouterOS command from ordered props. Props with an
// empty key are skipped, mirroring how the Python builder drops None.
func rosLine(path, verb string, props []prop) string {
	parts := []string{path, verb}
	for _, p := range props {
		parts = append(parts, p.key+"="+rosValue(p.value))
	}
	return strings.Join(parts, " ")
}

// -- blocks -----------------------------------------------------------

// mikrotikHeader is configs.system.Header's mikrotik method.
func mikrotikHeader(c *renderCtx) ([]string, error) {
	return []string{
		fmt.Sprintf("# %s - generated by barf. RouterOS v7 CLI.", c.host.Hostname),
		"# Sections mirror the fabric contract the VyOS/linux hosts implement:",
		"# WireGuard links, link addresses, eBGP to every spine, announced",
		"# networks, and geographic path weighting (origin-site large",
		"# communities in, local-pref out) when the host has a `site`.",
	}, nil
}

// mikrotikSSHConfig is configs.system.SshConfig's mikrotik method.
//
// RouterOS never reads key material back (write-only in the diff), so
// rotating a key must also change its trailing comment. `key-owner` is
// not a valid `add` parameter, so only user/key are sent.
func mikrotikSSHConfig(c *renderCtx) ([]string, error) {
	var lines []string
	for _, sshKey := range c.global.SSHKeys {
		lines = append(lines, rosLine("/user/ssh-keys", "add", []prop{
			{"user", mikrotikSSHUser},
			{"key", sshKey},
		}))
	}
	return append(lines, ""), nil
}

// mikrotikNTPConfig is configs.system.NtpConfig's mikrotik method:
// RouterOS owns only the client sync, serving LAN clients stays unmodeled.
func mikrotikNTPConfig(c *renderCtx) ([]string, error) {
	return []string{
		rosLine("/system/ntp/client", "set", []prop{
			{"enabled", "yes"},
			{"mode", "unicast"},
			{"servers", strings.Join(ntpServers, ",")},
		}),
		"",
	}, nil
}

// mikrotikBridges is configs.interfaces.Bridges: LAN/L2 bridges modeled
// in network.yml. barf owns the bridge by name, its L3 addresses, and
// its member ports.
func mikrotikBridges(c *renderCtx) ([]string, error) {
	var lines []string
	for i := range c.host.Interfaces {
		iface := &c.host.Interfaces[i]
		if !iface.IsBridge() {
			continue
		}
		add := "/interface/bridge add name=" + iface.Name
		if iface.Description != "" {
			add += fmt.Sprintf(" comment=\"barf: %s\"", iface.Description)
		}
		lines = append(lines, add)
		for _, member := range iface.Members {
			lines = append(lines, fmt.Sprintf(
				"/interface/bridge/port add bridge=%s interface=%s", iface.Name, member))
		}
		for _, addr := range iface.Addresses {
			lines = append(lines, fmt.Sprintf(
				"/ip/address add address=%s interface=%s comment=\"barf: %s address\"",
				addr.String(), iface.Name, iface.Name))
		}
		if len(iface.RA) > 0 {
			nd := "/ipv6/nd add interface=" + iface.Name
			if hopLimit := wgString(iface.RA, "hop_limit"); hopLimit != "" && hopLimit != "0" {
				nd += " hop-limit=" + hopLimit
			}
			advertiseDNS := "no"
			if truthy(iface.RA["advertise_dns"]) {
				advertiseDNS = "yes"
			}
			lines = append(lines, nd+" advertise-dns="+advertiseDNS)
		}
	}
	return append(lines, ""), nil
}

func truthy(value any) bool {
	switch typed := value.(type) {
	case nil:
		return false
	case bool:
		return typed
	case string:
		return typed != "" && typed != "false"
	case int:
		return typed != 0
	default:
		return true
	}
}

// mikrotikStaticWireGuard is configs.interfaces.StaticWireGuard: external
// peerings, not the Vault-derived fabric mesh.
func mikrotikStaticWireGuard(c *renderCtx) ([]string, error) {
	var lines []string
	for i := range c.host.Interfaces {
		iface := &c.host.Interfaces[i]
		if !iface.IsWireguard() || len(iface.Wireguard) == 0 {
			continue
		}
		wg := iface.Wireguard
		privateKey, err := c.secrets.HostSecret(c.host.Hostname, wgString(wg, "private_key_secret"))
		if err != nil {
			return nil, err
		}
		port := wgString(wg, "port")
		mtu := "1420"
		if iface.MTU != 0 {
			mtu = fmt.Sprint(iface.MTU)
		}

		lines = append(lines, rosLine("/interface/wireguard", "add", []prop{
			{"name", iface.Name},
			{"listen-port", port},
			{"mtu", mtu},
			{"private-key", privateKey},
			{"comment", fmt.Sprintf("barf: %s tunnel", iface.Name)},
		}))

		peers, _ := wg["peers"].([]any)
		for _, raw := range peers {
			peer, ok := raw.(map[string]any)
			if !ok {
				continue
			}
			allowed := wgStrings(peer, "allowed_ips")
			if allowed == nil {
				allowed = []string{"0.0.0.0/0", "::/0"}
			}
			props := []prop{
				{"interface", iface.Name},
				{"name", wgString(peer, "name")},
				{"public-key", wgString(peer, "public_key")},
				{"allowed-address", strings.Join(allowed, ",")},
			}
			if endpoint := wgString(peer, "endpoint"); endpoint != "" {
				peerPort := wgString(peer, "port")
				if peerPort == "" {
					peerPort = port
				}
				keepalive := wgString(peer, "keepalive")
				if keepalive == "" {
					keepalive = "10s"
				}
				props = append(props,
					prop{"endpoint-address", endpoint},
					prop{"endpoint-port", peerPort},
					prop{"persistent-keepalive", keepalive},
				)
			}
			lines = append(lines, rosLine("/interface/wireguard/peers", "add", props))
		}
		for _, addr := range iface.Addresses {
			lines = append(lines, fmt.Sprintf(
				"/ip/address add address=%s interface=%s comment=\"barf: %s address\"",
				addr.String(), iface.Name, iface.Name))
		}
	}
	return append(lines, ""), nil
}

// mikrotikFirewallGroups is configs.firewall.FirewallGroups' mikrotik
// method: address members split by family, interface lists nesting natively.
func mikrotikFirewallGroups(c *renderCtx) ([]string, error) {
	var lines []string
	for _, group := range c.host.Firewall.Address {
		for _, family := range []struct {
			version int
			path    string
		}{{4, "/ip"}, {6, "/ipv6"}} {
			for _, member := range group.MembersV(family.version) {
				line := fmt.Sprintf("%s/firewall/address-list add list=%s address=%s",
					family.path, group.Name, member.Address)
				if member.Comment != "" {
					line += fmt.Sprintf(" comment=\"%s\"", member.Comment)
				}
				lines = append(lines, line)
			}
		}
	}
	for _, group := range c.host.Firewall.Interface {
		add := "/interface/list add name=" + group.Name
		if len(group.Include) > 0 {
			add += " include=" + strings.Join(group.Include, ",")
		}
		lines = append(lines, add)
		for _, iface := range group.Interfaces {
			lines = append(lines, fmt.Sprintf(
				"/interface/list/member add list=%s interface=%s", group.Name, iface))
		}
	}
	return append(lines, ""), nil
}

// announcedNetworks is the host's own networks plus modeled transit link
// networks: transit link nets are announced (and tagged) like our own so
// every fabric session advertises identically.
func announcedNetworks(h *model.Host) []string {
	out := append([]string{}, h.Networks...)
	for _, transit := range h.BGP.Transit {
		out = append(out, transit.LinkNetwork)
	}
	return out
}

// mikrotikAnnouncedNetworks is configs.fabric.AnnouncedNetworks: the
// genprog-networks address-list backing BGP origination.
func mikrotikAnnouncedNetworks(c *renderCtx) ([]string, error) {
	var lines []string
	for _, network := range announcedNetworks(c.host) {
		lines = append(lines, fmt.Sprintf(
			"/ip/firewall/address-list add list=genprog-networks address=%s"+
				" comment=\"barf: announced to the fabric\"", network))
	}
	return append(lines, ""), nil
}

// mikrotikFabricWireGuard is configs.fabric.FabricWireGuard's mikrotik
// method.
//
// Unnumbered links (RFC 5549) get ND instead of an address: RAs teach us
// the peer's link-local. /ipv6/nd entries silently discard comment=, so
// none is rendered there: it would read as a forever-pending diff.
func mikrotikFabricWireGuard(c *renderCtx) ([]string, error) {
	var lines []string
	for _, link := range c.links {
		peer, err := c.peer(link)
		if err != nil {
			return nil, err
		}
		ourKeys, err := wireguardKeypair(c.secrets, link.KeyPath(c.host.Hostname))
		if err != nil {
			return nil, err
		}
		peerKeys, err := wireguardKeypair(c.secrets, link.KeyPath(peer.Hostname))
		if err != nil {
			return nil, err
		}
		interfaceName := fmt.Sprintf("wg%d", link.Port)

		lines = append(lines, rosLine("/interface/wireguard", "add", []prop{
			{"name", interfaceName},
			{"listen-port", fmt.Sprint(link.Port)},
			{"mtu", "1420"},
			{"private-key", ourKeys.Private},
			{"comment", fmt.Sprintf("barf: %s -> %s", link.A, link.B)},
		}))

		props := []prop{
			{"interface", interfaceName},
			{"name", peer.Hostname},
			{"public-key", peerKeys.Public},
			{"allowed-address", "0.0.0.0/0,::/0"},
		}
		if endpoint := peer.WGEndpoint(); endpoint != "" {
			props = append(props,
				prop{"endpoint-address", endpoint},
				prop{"endpoint-port", fmt.Sprint(link.Port)},
				prop{"persistent-keepalive", "10s"},
			)
		}
		lines = append(lines, rosLine("/interface/wireguard/peers", "add", props))

		if link.Unnumbered() {
			lines = append(lines,
				fmt.Sprintf("/ipv6/nd add interface=%s ra-interval=10s-15s", interfaceName),
				fmt.Sprintf("/ipv6/nd/prefix add prefix=none interface=%s"+
					" comment=\"barf: %s unnumbered BGP\"", interfaceName, peer.Hostname),
			)
		} else {
			lines = append(lines, fmt.Sprintf(
				"/ip/address add address=%s interface=%s comment=\"barf: %s link\"",
				link.GetIP(c.host.Hostname, true), interfaceName, peer.Hostname))
		}
	}
	return append(lines, ""), nil
}

// mikrotikSiteWeighting is configs.fabric.SiteWeighting's mikrotik method.
func mikrotikSiteWeighting(c *renderCtx) ([]string, error) {
	if c.originSite == nil {
		return []string{""}, nil
	}
	asn := c.communityAS
	transit := c.host.BGP.Transit

	var lines []string
	for _, network := range announcedNetworks(c.host) {
		lines = append(lines, fmt.Sprintf(
			"/routing/filter/rule add chain=genprog-out comment=\"barf: origin-site tag\""+
				" rule=\"if (dst == %s) { set bgp-large-communities %d:%d:%d; accept }\"",
			network, asn, siteOriginFunc, c.originSite.ID))
	}
	for _, t := range transit {
		lines = append(lines, fmt.Sprintf(
			"/routing/filter/rule add chain=genprog-out"+
				" comment=\"barf: reflect %s (AS %d) into the fabric\""+
				" rule=\"if (dst-len != 0 && bgp-input-remote-as == %d) { accept }\"",
			t.Name, t.RemoteAS, t.RemoteAS))
	}
	if len(transit) > 0 {
		lines = append(lines, "/routing/filter/rule add chain=genprog-out"+
			" comment=\"barf: no other re-export\" rule=\"reject\"")
	} else {
		lines = append(lines, "/routing/filter/rule add chain=genprog-out rule=\"accept\"")
	}
	for _, entry := range c.importRules {
		for _, rule := range entry.Rules {
			lines = append(lines, fmt.Sprintf(
				"/routing/filter/rule add chain=genprog-in-%s comment=\"barf: origin site %d\""+
					" rule=\"if (bgp-large-communities includes %d:%d:%d)"+
					" { set bgp-local-pref %d; accept }\"",
				entry.Site, rule.SiteID, asn, siteOriginFunc, rule.SiteID, rule.LocalPref))
		}
		lines = append(lines, fmt.Sprintf(
			"/routing/filter/rule add chain=genprog-in-%s"+
				" comment=\"barf: untagged fallthrough\" rule=\"accept\"", entry.Site))
	}
	return append(lines, ""), nil
}

// mikrotikFabricBGP is configs.fabric.FabricBGP's mikrotik method.
//
// Unnumbered connections: local.address is the INTERFACE, no
// remote.address (the peer's link-local is discovered via ND), and
// afi=ip,ipv6 is mandatory -- the default afi=ip establishes but
// exchanges zero prefixes.
func mikrotikFabricBGP(c *renderCtx) ([]string, error) {
	template := fmt.Sprintf(
		"/routing/bgp/template add name=genprog-fabric as=%d hold-time=30s keepalive-time=10s",
		c.host.ASN)
	if len(announcedNetworks(c.host)) > 0 {
		template += " output.network=genprog-networks"
	}
	lines := []string{template}

	for _, link := range c.links {
		peer, err := c.peer(link)
		if err != nil {
			return nil, err
		}
		interfaceName := fmt.Sprintf("wg%d", link.Port)

		instance := ""
		if c.host.BGP.Instance != "" {
			instance = " instance=" + c.host.BGP.Instance
		}
		policy := ""
		if len(rulesFor(c.importRules, peer.Site)) > 0 {
			policy += " input.filter=genprog-in-" + peer.Site
		}
		if c.originSite != nil {
			policy += " output.filter-chain=genprog-out"
		}

		if link.Unnumbered() {
			lines = append(lines, fmt.Sprintf(
				"/routing/bgp/connection add name=%s templates=genprog-fabric%s"+
					" local.address=%s local.role=ebgp remote.as=%d afi=ip,ipv6%s"+
					" comment=\"barf: %s\"",
				peer.Hostname, instance, interfaceName, peer.ASN, policy, peer.Hostname))
		} else {
			lines = append(lines, fmt.Sprintf(
				"/routing/bgp/connection add name=%s templates=genprog-fabric%s"+
					" remote.address=%s remote.as=%d local.address=%s local.role=ebgp%s"+
					" comment=\"barf: %s\"",
				peer.Hostname, instance, link.GetIP(peer.Hostname, false), peer.ASN,
				link.GetIP(c.host.Hostname, false), policy, peer.Hostname))
		}
	}
	return append(lines, ""), nil
}

// mikrotikTransitBGP is configs.fabric.TransitBGP: the transit sessions
// barf owns, reproducing the retired hand-written `export` chain.
func mikrotikTransitBGP(c *renderCtx) ([]string, error) {
	transit := c.host.BGP.Transit
	if len(transit) == 0 {
		return nil, nil
	}

	var lines []string
	for _, t := range transit {
		lines = append(lines,
			fmt.Sprintf("/routing/filter/rule add chain=genprog-out-transit"+
				" comment=\"barf: export fabric routes to %s (AS %d)\""+
				" rule=\"if (dst-len != 0 && bgp-output-remote-as == %d"+
				" && bgp-input-remote-as != %d) {accept}\"",
				t.Name, t.RemoteAS, t.RemoteAS, t.RemoteAS),
			fmt.Sprintf("/routing/filter/rule add chain=genprog-out-transit"+
				" comment=\"barf: reflect %s routes to the fabric\""+
				" rule=\"if (dst-len != 0 && bgp-output-remote-as != %d"+
				" && bgp-input-remote-as == %d) {accept}\"",
				t.Name, t.RemoteAS, t.RemoteAS),
			fmt.Sprintf("/routing/filter/rule add chain=genprog-out-transit"+
				" comment=\"barf: export %s link prefix to the fabric\""+
				" rule=\"if (dst-len != 0 && protocol connected && dst in %s"+
				" && bgp-output-remote-as != %d) {accept}\"",
				t.Name, t.ExportSupernet, t.RemoteAS),
			fmt.Sprintf("/routing/filter/rule add chain=genprog-out-transit"+
				" comment=\"barf: export fabric link prefixes to %s\""+
				" rule=\"if (dst-len != 0 && protocol connected && dst in %s"+
				" && bgp-output-remote-as == %d) {accept}\"",
				t.Name, fabricLinkNet, t.RemoteAS),
		)
	}

	internal := make([]string, 0, len(c.host.Networks))
	for _, network := range c.host.Networks {
		internal = append(internal, "dst in "+network)
	}
	lines = append(lines, fmt.Sprintf(
		"/routing/filter/rule add chain=genprog-out-transit"+
			" comment=\"barf: announce internal prefixes, drop other connected\""+
			" rule=\"if (protocol connected && (%s)) {accept} else {reject}\"",
		strings.Join(internal, " or ")))
	lines = append(lines, "")
	lines = append(lines, fmt.Sprintf(
		"/routing/bgp/template add name=genprog-transit as=%d routing-table=main", c.host.ASN))

	for _, t := range transit {
		instance := ""
		if c.host.BGP.Instance != "" {
			instance = " instance=" + c.host.BGP.Instance
		}
		lines = append(lines, fmt.Sprintf(
			"/routing/bgp/connection add name=%s templates=genprog-transit%s"+
				" remote.address=%s remote.as=%d local.role=ebgp"+
				" output.filter-chain=genprog-out-transit comment=\"barf: %s transit\"",
			t.Name, instance, t.RemoteAddress, t.RemoteAS, t.Name))
	}
	return lines, nil
}
