---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netbox-config
data:
  custom_pipeline.py: |
    # from django.contrib.auth.models import Group # For NetBox < 4.0.0
    from netbox.authentication import Group # For NetBox >= 4.0.0

    class AuthFailed(Exception):
        pass

    def add_groups(response, user, backend, *args, **kwargs):
        try:
            groups = response['groups']
        except KeyError:
            pass

        # Add all groups from OAuth token
        for group in groups:
            group, created = Group.objects.get_or_create(name=group)
            # group.user_set.add(user) # For NetBox < 4.0.0
            user.groups.add(group) # For NetBox >= 4.0.0

    def remove_groups(response, user, backend, *args, **kwargs):
        try:
            groups = response['groups']
        except KeyError:
            # Remove all groups if no groups in OAuth token
            user.groups.clear()
            pass

        # Get all groups for user
        user_groups = [item.name for item in user.groups.all()]
        # Get user groups that are not part of the OAuth token
        delete_groups = list(set(user_groups) - set(groups))

        # Delete groups not included in the OAuth token
        for delete_group in delete_groups:
            group = Group.objects.get(name=delete_group)
            # group.user_set.remove(user) # For NetBox < 4.0.0
            user.groups.remove(group) # For NetBox >= 4.0.0


    def set_roles(response, user, backend, *args, **kwargs):
        # Remove Roles temporarily
        user.is_superuser = False
        user.is_staff = False
        try:
            groups = response['groups']
        except KeyError:
            # When no groups are set
            # save the user without Roles
            user.save()
            pass

        # Set roles when role groups (superuser or staff) are present
        user.is_superuser = True if 'admin' in groups else False
        user.is_staff = True if 'admin' in groups else False
        user.save()
  authentik.py: |
    from os import environ

    def _read_secret(secret_name, default=None):
        try:
            f = open('/run/secrets/' + secret_name, 'r', encoding='utf-8')
        except EnvironmentError:
            return default
        else:
            with f:
                return f.readline().strip()

    SOCIAL_AUTH_OIDC_OIDC_ENDPOINT = environ.get('SOCIAL_AUTH_OIDC_OIDC_ENDPOINT')
    SOCIAL_AUTH_OIDC_KEY = environ.get('SOCIAL_AUTH_OIDC_KEY')
    SOCIAL_AUTH_OIDC_SECRET = _read_secret('oidc_secret', environ.get('SOCIAL_AUTH_OIDC_SECRET', ''))
    SOCIAL_AUTH_OIDC_SCOPE = environ.get('SOCIAL_AUTH_OIDC_SCOPE').split(' ')
    LOGOUT_REDIRECT_URL = environ.get('LOGOUT_REDIRECT_URL')

    SOCIAL_AUTH_PIPELINE = (
        ###################
        # Default pipelines
        ###################

        # Get the information we can about the user and return it in a simple
        # format to create the user instance later. In some cases the details are
        # already part of the auth response from the provider, but sometimes this
        # could hit a provider API.
        'social_core.pipeline.social_auth.social_details',

        # Get the social uid from whichever service we're authing thru. The uid is
        # the unique identifier of the given user in the provider.
        'social_core.pipeline.social_auth.social_uid',

        # Verifies that the current auth process is valid within the current
        # project, this is where emails and domains whitelists are applied (if
        # defined).
        'social_core.pipeline.social_auth.auth_allowed',

        # Checks if the current social-account is already associated in the site.
        'social_core.pipeline.social_auth.social_user',

        # Make up a username for this person, appends a random string at the end if
        # there's any collision.
        'social_core.pipeline.user.get_username',

        # Send a validation email to the user to verify its email address.
        # Disabled by default.
        # 'social_core.pipeline.mail.mail_validation',

        # Associates the current social details with another user account with
        # a similar email address. Disabled by default.
        # 'social_core.pipeline.social_auth.associate_by_email',

        # Create a user account if we haven't found one yet.
        'social_core.pipeline.user.create_user',

        # Create the record that associates the social account with the user.
        'social_core.pipeline.social_auth.associate_user',

        # Populate the extra_data field in the social record with the values
        # specified by settings (and the default ones like access_token, etc).
        'social_core.pipeline.social_auth.load_extra_data',

        # Update the user record with any changed info from the auth service.
        'social_core.pipeline.user.user_details',


        ###################
        # Custom pipelines
        ###################
        # Set authentik Groups
        'netbox.custom_pipeline.add_groups',
        'netbox.custom_pipeline.remove_groups',
        # Set Roles
        'netbox.custom_pipeline.set_roles'
    )
  ldap_config.py: |
    from importlib import import_module
    from os import environ

    import ldap
    from django_auth_ldap.config import LDAPSearch


    # Read secret from file
    def _read_secret(secret_name, default=None):
        try:
            f = open('/run/secrets/' + secret_name, 'r', encoding='utf-8')
        except EnvironmentError:
            return default
        else:
            with f:
                return f.readline().strip()

    # Import and return the group type based on string name
    def _import_group_type(group_type_name):
        mod = import_module('django_auth_ldap.config')
        try:
            return getattr(mod, group_type_name)()
        except:
            return None

    # Server URI
    AUTH_LDAP_SERVER_URI = environ.get('AUTH_LDAP_SERVER_URI', '')

    # The following may be needed if you are binding to Active Directory.
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_REFERRALS: 0
    }

    AUTH_LDAP_BIND_AS_AUTHENTICATING_USER = environ.get('AUTH_LDAP_BIND_AS_AUTHENTICATING_USER', 'False').lower() == 'true'

    # Set the DN and password for the NetBox service account if needed.
    if not AUTH_LDAP_BIND_AS_AUTHENTICATING_USER:
        AUTH_LDAP_BIND_DN = environ.get('AUTH_LDAP_BIND_DN', '')
        AUTH_LDAP_BIND_PASSWORD = _read_secret('auth_ldap_bind_password', environ.get('AUTH_LDAP_BIND_PASSWORD', ''))

    # Set a string template that describes any user’s distinguished name based on the username.
    AUTH_LDAP_USER_DN_TEMPLATE = environ.get('AUTH_LDAP_USER_DN_TEMPLATE', None)

    # Enable STARTTLS for ldap authentication.
    AUTH_LDAP_START_TLS = environ.get('AUTH_LDAP_START_TLS', 'False').lower() == 'true'

    # Include this setting if you want to ignore certificate errors. This might be needed to accept a self-signed cert.
    # Note that this is a NetBox-specific setting which sets:
    #     ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_NEVER)
    LDAP_IGNORE_CERT_ERRORS = environ.get('LDAP_IGNORE_CERT_ERRORS', 'False').lower() == 'true'

    # Include this setting if you want to validate the LDAP server certificates against a CA certificate directory on your server
    # Note that this is a NetBox-specific setting which sets:
    #     ldap.set_option(ldap.OPT_X_TLS_CACERTDIR, LDAP_CA_CERT_DIR)
    LDAP_CA_CERT_DIR = environ.get('LDAP_CA_CERT_DIR', None)

    # Include this setting if you want to validate the LDAP server certificates against your own CA.
    # Note that this is a NetBox-specific setting which sets:
    #     ldap.set_option(ldap.OPT_X_TLS_CACERTFILE, LDAP_CA_CERT_FILE)
    LDAP_CA_CERT_FILE = environ.get('LDAP_CA_CERT_FILE', None)

    AUTH_LDAP_USER_SEARCH_BASEDN = environ.get('AUTH_LDAP_USER_SEARCH_BASEDN', '')
    AUTH_LDAP_USER_SEARCH_ATTR = environ.get('AUTH_LDAP_USER_SEARCH_ATTR', 'sAMAccountName')
    AUTH_LDAP_USER_SEARCH_FILTER: str = environ.get(
        'AUTH_LDAP_USER_SEARCH_FILTER', f'({AUTH_LDAP_USER_SEARCH_ATTR}=%(user)s)'
    )

    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        AUTH_LDAP_USER_SEARCH_BASEDN, ldap.SCOPE_SUBTREE, AUTH_LDAP_USER_SEARCH_FILTER
    )

    # This search ought to return all groups to which the user belongs. django_auth_ldap uses this to determine group
    # heirarchy.

    AUTH_LDAP_GROUP_SEARCH_BASEDN = environ.get('AUTH_LDAP_GROUP_SEARCH_BASEDN', '')
    AUTH_LDAP_GROUP_SEARCH_CLASS = environ.get('AUTH_LDAP_GROUP_SEARCH_CLASS', 'group')

    AUTH_LDAP_GROUP_SEARCH_FILTER: str = environ.get(
        'AUTH_LDAP_GROUP_SEARCH_FILTER', f'(objectclass={AUTH_LDAP_GROUP_SEARCH_CLASS})'
    )
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        AUTH_LDAP_GROUP_SEARCH_BASEDN, ldap.SCOPE_SUBTREE, AUTH_LDAP_GROUP_SEARCH_FILTER
    )
    AUTH_LDAP_GROUP_TYPE = _import_group_type(environ.get('AUTH_LDAP_GROUP_TYPE', 'GroupOfNamesType'))

    # Define a group required to login.
    AUTH_LDAP_REQUIRE_GROUP = environ.get('AUTH_LDAP_REQUIRE_GROUP_DN')

    # Define special user types using groups. Exercise great caution when assigning superuser status.
    AUTH_LDAP_USER_FLAGS_BY_GROUP = {}

    if AUTH_LDAP_REQUIRE_GROUP is not None:
        AUTH_LDAP_USER_FLAGS_BY_GROUP = {
            "is_active": environ.get('AUTH_LDAP_REQUIRE_GROUP_DN', ''),
            "is_staff": environ.get('AUTH_LDAP_IS_ADMIN_DN', ''),
            "is_superuser": environ.get('AUTH_LDAP_IS_SUPERUSER_DN', '')
        }

    # For more granular permissions, we can map LDAP groups to Django groups.
    AUTH_LDAP_FIND_GROUP_PERMS = environ.get('AUTH_LDAP_FIND_GROUP_PERMS', 'True').lower() == 'true'
    AUTH_LDAP_MIRROR_GROUPS = environ.get('AUTH_LDAP_MIRROR_GROUPS', '').lower() == 'true'

    # Cache groups for one hour to reduce LDAP traffic
    AUTH_LDAP_CACHE_TIMEOUT = int(environ.get('AUTH_LDAP_CACHE_TIMEOUT', 3600))

    # Populate the Django user from the LDAP directory.
    AUTH_LDAP_USER_ATTR_MAP = {
        "first_name": environ.get('AUTH_LDAP_ATTR_FIRSTNAME', 'givenName'),
        "last_name": environ.get('AUTH_LDAP_ATTR_LASTNAME', 'sn'),
        "email": environ.get('AUTH_LDAP_ATTR_MAIL', 'mail')
    }

    # Update user object with the latest values from the LDAP directory every time the user logs in.
    AUTH_LDAP_ALWAYS_UPDATE_USER = environ.get('AUTH_LDAP_ALWAYS_UPDATE_USER', 'True').lower() == 'true'
