apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: netbox
  replicas: 1
  template:
    metadata:
      labels:
        app: netbox
    spec:
      containers:
      - name: netbox
        image: netboxcommunity/netbox:v4.5-4.0.1
        resources: {}
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: netbox-db-app
                key: dbname
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: netbox-db-app
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: netbox-db-app
                key: password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: netbox-db-app
                key: host
        envFrom:
        - configMapRef:
            name: netbox-env
        - secretRef:
            name: netbox-secrets
        - secretRef:
            name: netbox-oidc
        volumeMounts:
        # Configs
        - name: netbox-config
          subPath: authentik.py
          mountPath: /etc/netbox/config/authentik.py
        - name: netbox-config
          subPath: custom_pipeline.py
          mountPath: /opt/netbox/netbox/netbox/custom_pipeline.py
        # PVC
        - name: netbox-media
          mountPath: /opt/netbox/netbox/media
      volumes:
        - name: netbox-media
          persistentVolumeClaim:
            claimName: netbox-media
        - name: netbox-config
          configMap:
            name: netbox-config
            items:
            - key: authentik.py
              path: authentik.py
            - key: custom_pipeline.py
              path: custom_pipeline.py
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-worker
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: netbox-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: netbox-worker
    spec:
      containers:
      - name: netbox-worker
        image: netboxcommunity/netbox:v4.5-4.0.1
        command:
          - /opt/netbox/venv/bin/python
          - /opt/netbox/netbox/manage.py
          - rqworker
        resources: {}
        env:
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: netbox-db-app
                key: dbname
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: netbox-db-app
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: netbox-db-app
                key: password
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: netbox-db-app
                key: host
        envFrom:
        - configMapRef:
            name: netbox-env
        - secretRef:
            name: netbox-secrets
        - secretRef:
            name: netbox-oidc
        volumeMounts:
        # Configs
        - name: netbox-config
          subPath: authentik.py
          mountPath: /etc/netbox/config/authentik.py
        - name: netbox-config
          subPath: custom_pipeline.py
          mountPath: /opt/netbox/netbox/netbox/custom_pipeline.py
        # PVC
        - name: netbox-media
          mountPath: /opt/netbox/netbox/media
      volumes:
        - name: netbox-media
          persistentVolumeClaim:
            claimName: netbox-media
        - name: netbox-config
          configMap:
            name: netbox-config
            items:
            - key: custom_pipeline.py
              path: custom_pipeline.py
            - key: authentik.py
              path: authentik.py
