---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  storageClassName: ceph-rbd-xfs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox-redis
spec:
  selector:
    matchLabels:
      app: netbox-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: netbox-redis
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:8.1-alpine
        command:
          - valkey-server
          - --appendonly
          - "yes"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: netbox-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: netbox-redis
  selector:
    app: netbox-redis
  type: ClusterIP