- hosts: etcd_masters
  become: true
  roles:
    - role: setup_etcd
  vars:
    etcd_init_hosts: "{{ hostvars | etcd_hosts(2380, True) }}"

- hosts: k8s_app
  become: true
  roles:
    - role: update_packages
      appserver_packages: true
    - role: setup_flanneld
    - role: setup_k8s
  vars:
    etcd_hosts: "{{ hostvars | etcd_hosts(2379, False) }}"
