- hosts: database
  become: true
  roles:
    - role: setup_postgres
      postgres_hba_hosts:
        - "host    all             all             172.16.0.0/12           md5"
        - "host    all             all             192.168.0.0/16          md5"
