- hosts: all_hosts
  become: true
  roles:
    - role: cloudalchemy.node_exporter
      when: prom_node_exporter and prom_node_exporter == true
    - role: setup_auditbeat
    - role: setup_filebeat
  vars:
    elastic_host: 192.168.3.2

- hosts: all_hosts
  become: true
  roles:
    - role: setup_filebeat
  vars:
    elastic_host: 192.168.3.2
