# One time setup provisoning.
- import_playbook: provision_bootstrap_servers.yml

# Firewall update
- import_playbook: task_update_firewall.yml

# Repeatable provisioning/updating for cluster backbone.
# tinc VPN, admin user, central stats collection.
- import_playbook: provision_cluster_backbone.yml

- import_playbook: provision_node_exporter.yml

# Database server setup
- import_playbook: provision_database_server.yml

# Docker servers setup.
- import_playbook: provision_docker_server.yml
