---
# debops tinc without the debops common bits or many variables

- name: "tincd - Install"
  package:
    name: "tinc"
    state: present

- name: "tincd - Create directories"
  file:
    path: "/etc/tinc/{{ tincd_netname }}/hosts/{{ ansible_nodename | replace('-', '_') }}.d"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "tincd - Create main config"
  template:
    src: "tinc.conf.j2"
    dest: "/etc/tinc/{{ tincd_netname }}/tinc.conf"
    owner: root
    group: root
    mode: 0644
  register: tinc_conf

- name: "tincd - Generate up-down scripts."
  template:
    src: "{{ item }}.j2"
    dest: "/etc/tinc/{{ tincd_netname }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - "tinc-up"
    - "tinc-down"

- name: "tincd - Generate nets.boot."
  template:
    src: "nets.boot.j2"
    dest: "/etc/tinc/nets.boot"
    owner: root
    group: root
    mode: 0644

# RSA key management
- name: "tincd - Ensure that sensitive files are excluded from version control"
  template:
    src: "gitignore.j2"
    dest: "/etc/tinc/.gitignore"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "tincd - Generate keypairs"
  shell: "tincd -n {{ tincd_netname }} -K 4096"
  args:
    creates: "/etc/tinc/{{ tincd_netname }}/rsa_key.priv"

# Tinc host configuration
- name: "tincd - Create persistent copy of host public key"
  command: cp /etc/tinc/{{ tincd_netname }}/hosts/{{ ansible_nodename | replace("-", "_") }}
              /etc/tinc/{{ tincd_netname }}/hosts/{{ ansible_nodename | replace("-", "_") + ".d/99_rsa-public-key" }}
  args:
    creates: /etc/tinc/{{ tincd_netname }}/hosts/{{ ansible_nodename | replace("-", "_") + ".d/99_rsa-public-key" }}

- name: "tincd - Get public IP"
  ipify_facts:

- name: "tincd - Generate host config header"
  template:
    src: "host-config.j2"
    dest: "/etc/tinc/{{ tincd_netname }}/hosts/{{ ansible_nodename | replace('-', '_') }}.d/00_host-config"
    owner: root
    group: root
    mode: 0640

- name: "tincd - Generate full host config"
  assemble:
    src: "/etc/tinc/{{ tincd_netname }}/hosts/{{ ansible_nodename | replace('-', '_') }}.d"
    dest: "/etc/tinc/{{ tincd_netname }}/hosts/{{ ansible_nodename | replace('-', '_') }}"
    owner: root
    group: root
    mode: 0640
  register: host_config

# Tinc host configuration distribution
- name: "tincd - Upload public keys from hosts"
  fetch:
    src: "/etc/tinc/{{ tincd_netname }}/hosts/{{ ansible_nodename | replace('-', '_') }}"
    dest: "{{ '/tmp/tinc/' + tincd_netname + '/' + ansible_nodename | replace('-', '_') }}"
    flat: True

- name: "tincd - Download public keys for all hosts"
  copy:
    src: "{{ '/tmp/tinc/' + tincd_netname + '/'}}"
    dest: "/etc/tinc/{{ tincd_netname }}/hosts/"
    owner: "root"
    group: "root"
    mode: "0640"
  register: tinc_keys

# systemd
- name: "tincd - Update systemd daemon configuration and restart daemon"
  systemd:
    name: tinc
    enabled: true
    state: restarted
  when: tinc_conf.changed or host_config.changed or tinc_keys.changed
