- name: dnsmasq - Install
  package:
    name: dnsmasq
    state: present

- name: dnsmasq - Update config
  template:
    src: 00-cluster.j2
    dest: /etc/dnsmasq.d/00-cluster.conf

- name: dnsmasq - Restart
  service:
    name: "dnsmasq"
    enabled: true
    state: restarted
