---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: sentry
spec:
  replicas: 3
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: sentry
spec:
  replicas: 2
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 16Gi
  keeperClusterRef:
    name: sentry
  containerTemplate:
    image:
      repository: clickhouse/clickhouse-server
      tag: "25.3.6.10034"
