---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: sentry
spec:
  replicas: 3
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 32Gi
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: sentry
spec:
  replicas: 2
  containerTemplate:
    resources:
      requests:
        cpu: "1"
        memory: "6Gi"
      limits:
        cpu: "2"
        memory: "8Gi"
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 32Gi
  keeperClusterRef:
    name: sentry
  containerTemplate:
    image:
      repository: clickhouse/clickhouse-server
      tag: "25.3"
