---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sentry-db
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18
  instances: 2
  primaryUpdateStrategy: unsupervised
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: generalprogramming.org/no-database
                operator: DoesNotExist
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 16Gi
      storageClassName: local-path
    initdb:
      database: sentry
      owner: sentry
  postgresql:
    parameters:
      max_connections: "284"
      shared_buffers: "1GB"
