"""initial

Revision ID: da0fa2c6667c
Revises:
Create Date: 2019-03-20 18:41:30.511507

"""

# revision identifiers, used by Alembic.
revision = "da0fa2c6667c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
