---
- name: "K8S - Prepare environment"
  include_tasks: prepare.yml

- name: "K8S - Certificates"
  include_tasks: update_certs.yml

- name: "K8S - Tokens"
  include_tasks: update_tokens.yml

- name: "K8S - Client config"
  include_tasks: client_config.yml

- name: "K8S - Server config"
  include_tasks: server_config.yml

- name: "K8S - systemd daemon-reload"
  systemd:
    daemon_reload: yes

- name: "K8S - Online kubelet"
  systemd:
    name: kubelet
    state: started
    enabled: yes

- name: "K8S - Online kube-proxy"
  systemd:
    name: kube-proxy
    state: started
    enabled: yes

- name: "K8S - Setup addons"
  include_tasks: addons.yml
  when: kube_master
