---
- name: "Postgres - Apt repo"
  apt_repository:
    repo: '{{ item }}'
    state: present
  loop:
    - 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'

- name: "Postgres - Install"
  package:
    name: 'postgresql-{{ postgres_version }}'
    state: latest

- name: "Postgres - enable conf.d"
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    line: include_dir = 'conf.d'

- name: "Postgres - hba config"
  template:
    src: "pg_hba.j2"
    dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0644"
  register: pg_conf_hba

- name: "Postgres - Create conf.d"
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0755
  loop:
    - "/etc/postgresql/{{ postgres_version }}/main/conf.d/"

- name: "Postgres - confd config"
  template:
    src: "confd_ansible.j2"
    dest: "/etc/postgresql/{{ postgres_version }}/main/conf.d/00-ansible.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0644"
  register: postgres_confd_00

- name: "Postgres - Update systemd daemons configuration and restart daemons"
  service:
    name: "postgresql"
    enabled: true
    state: restarted
  when: pg_conf_hba.changed or postgres_confd_00.changed
