---
netbase__default_hosts:

  - '127.0.0.1': [ 'localhost' ]
  - '127.0.1.1': []
  - '::1':       [ 'localhost', 'ip6-localhost', 'ip6-loopback' ]
  - 'ff02::1':   [ 'ip6-allnodes' ]
  - 'ff02::2':   [ 'ip6-allrouters' ]

  - name:  '{{ netbase__host_ipv4_address }}'
    value: '{{ netbase__domain_host_entry }}'
    separator: '{{ True
                   if (netbase__host_ipv4_address == "127.0.1.1" and
                       (ansible_local|d() and ansible_local.netbase|d() and
                        ansible_local.netbase.self_domain_source not in [ "dns" ]))
                   else False }}'
