apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: victoriametrics
resources:
  - ../base
  - cluster.yaml
  - vmagent.yaml
  - vmalert.yaml
  - ingress-vmalert.yaml
  - sea1_scrape.yaml
  - scrape-sea1-core-node-exporter.yaml
  - consul-sd-secret.yaml
  - scrape-kubevirt.yaml
  - scrape-cilium.yaml
  - alerts-kubevirt.yaml
