apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: victoriametrics
spec:
  selectAllByDefault: true
  replicaCount: 1
  inlineRelabelConfig:
    - target_label: "dc"
      replacement: "sea1"
    - target_label: "cluster"
      replacement: "sea1-k8s"
  extraArgs:
    enableTCP6: "true"
  serviceSpec:
    spec:
      type: ClusterIP
    metadata:
      annotations:
        tailscale.com/expose: "true"
        tailscale.com/hostname: "svc-vmagent-sea1"
  remoteWrite:
    - url: "http://vminsert-sea1-victoriametrics.victoriametrics.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
    - url: "http://vminsert.fmt2.generalprogramming.org:8480/insert/0/prometheus/api/v1/write"
