---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: docspell-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie
  instances: 2
  primaryUpdateStrategy: unsupervised
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
  storage:
    storageClass: local-path
    size: 4Gi
  bootstrap:
    initdb:
      database: docspell
      owner: docspell
