version: "3.6"

x-default-settings: &default_settings
  restart: always
  deploy:
    restart_policy:
      condition: any
  env_file: .env

services:
  redis:
    << : *default_settings
    image: redis:alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    networks:
      - librenms

  memcached:
    << : *default_settings
    image: 'memcached:alpine'
    networks:
      - librenms

  rrdcached:
    << : *default_settings
    image: crazymax/rrdcached
    container_name: librenms_rrdcached
    volumes:
      - "/srv/var/librenms/rrd:/data/db"
      - "/srv/var/librenms/rrd-journal:/data/journal"
    environment:
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    networks:
      - librenms

  smtp:
    << : *default_settings
    image: juanluisbaptiste/postfix
    container_name: librenms_smtp
    environment:
      - "SERVER_HOSTNAME=nms.generalprogramming.org"
    networks:
      - librenms

  librenms:
    << : *default_settings
    image: librenms/librenms:latest
    container_name: librenms
    domainname: generalprogramming.org
    hostname: nms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=8000
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:nms.generalprogramming.org
    depends_on:
      - memcached
      - rrdcached
      - smtp
    volumes:
      - "/srv/var/librenms/data:/data"
    environment:
      - "DB_TIMEOUT=60"
    networks:
      - librenms
      - publicweb

  dispatcher:
    << : *default_settings
    image: librenms/librenms:latest
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    domainname: generalprogramming.org
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "/srv/var/librenms/data:/data"
    environment:
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
      - "SIDECAR_DISPATCHER=1"
    networks:
      - librenms

networks:
  librenms:
    driver: overlay
  publicweb:
    driver: overlay
    external: true
