version: "3.6"
services:
  # ftb-infinity-evolved:
  #   build: .
  #   image: registry.generalprogramming.org/minecraft-base:8
  #   volumes:
  #     - /srv/minecraft/globalroot:/root
  #     - /srv/minecraft/ftb-infinity-evolved/data:/data
  #     - /srv/minecraft/ftb-infinity-evolved/ssh:/etc/ssh
  #   ports:
  #     - target: 22
  #       published: 2222
  #       mode: ingress
  #     - target: 25565
  #       published: 25567
  #       mode: ingress
  #   deploy:
  #     labels:
  #       - traefik.enable=true
  #       - traefik.port=8123
  #       - traefik.docker.network=publicweb
  #       # Routes
  #       - traefik.frontend.rule=Host:ftbinfdynmap.nepeat.com
  #     restart_policy:
  #       condition: any
  #   networks:
  #     - minecraft
  #     - publicweb

  # gay-space-communism:
  #   build: .
  #   image: registry.generalprogramming.org/minecraft-base:8
  #   volumes:
  #     - /srv/minecraft/globalroot:/root
  #     - /srv/minecraft/gay-space-communism/data:/data
  #     - /srv/minecraft/gay-space-communism/ssh:/etc/ssh
  #   ports:
  #     - target: 22
  #       published: 2223
  #       mode: ingress
  #     - target: 25565
  #       published: 25568
  #       mode: ingress
  #   deploy:
  #     labels:
  #       - traefik.enable=true
  #       - traefik.port=8123
  #       - traefik.docker.network=publicweb
  #       # Routes
  #       - traefik.frontend.rule=Host:gaysovietmaps.nepeat.com
  #     restart_policy:
  #       condition: any
  #   networks:
  #     - minecraft
  #     - publicweb

  # offbeateggs:
  #   build: .
  #   image: registry.generalprogramming.org/minecraft-base:8
  #   volumes:
  #     - /srv/minecraft/globalroot:/root
  #     - /srv/minecraft/offbeateggs/data:/data
  #     - /srv/minecraft/offbeateggs/ssh:/etc/ssh
  #   ports:
  #     - target: 22
  #       published: 2224
  #       mode: ingress
  #     - target: 25565
  #       published: 25569
  #       mode: ingress
  #     - target: 25566
  #       published: 25570
  #       mode: ingress
  #   networks:
  #     - minecraft

  # chirstmaspack:
  #   build: .
  #   image: registry.generalprogramming.org/minecraft-base:8
  #   volumes:
  #     - /srv/minecraft/globalroot:/root
  #     - /srv/minecraft/chirstmaspack/data:/data
  #     - /srv/minecraft/chirstmaspack/ssh:/etc/ssh
  #   ports:
  #     - target: 22
  #       published: 2225
  #       mode: ingress
  #     - target: 25565
  #       published: 25571
  #       mode: ingress
  #   networks:
  #     - minecraft

  sarenevanilla:
    build: .
    image: registry.generalprogramming.org/minecraft-base:8
    volumes:
      - /srv/minecraft/globalroot:/root
      - /srv/minecraft/sarene/data:/data
      - /srv/minecraft/sarene/ssh:/etc/ssh
    ports:
      - target: 22
        published: 2226
        mode: ingress
      - target: 25565
        published: 25577
        mode: ingress
    networks:
      - minecraft

  uwuvanilla:
    build:
      context: .
      dockerfile: Dockerfile-17
    image: registry.generalprogramming.org/minecraft-base:17
    volumes:
      - /srv/minecraft/globalroot:/root
      - /srv/minecraft/uwuvanilla/data:/data
      - /srv/minecraft/uwuvanilla/ssh:/etc/ssh
    ports:
      - target: 22
        published: 2227
        mode: ingress
      - target: 25565
        published: 25578
        mode: ingress
    networks:
      - minecraft

  uwuftb:
    build: .
    image: registry.generalprogramming.org/minecraft-base:8
    volumes:
      - /srv/minecraft/globalroot:/root
      - /srv/minecraft/uwuftb/data:/data
      - /srv/minecraft/uwuftb/ssh:/etc/ssh
    ports:
      - target: 22
        published: 2228
        mode: ingress
      - target: 25565
        published: 25579
        mode: ingress
    networks:
      - minecraft

  moxvanilla:
    build:
      context: .
      dockerfile: Dockerfile-17
    image: registry.generalprogramming.org/minecraft-base:17
    volumes:
      - /srv/minecraft/globalroot:/root
      - /srv/minecraft/mox_vanilla/data:/data
      - /srv/minecraft/mox_vanilla/ssh:/etc/ssh
    ports:
      - target: 22
        published: 2229
        mode: ingress
      - target: 25565
        published: 25580
        mode: ingress
    networks:
      - minecraft

  toast:
    build: .
    image: registry.generalprogramming.org/minecraft-base:8
    volumes:
      - /srv/minecraft/globalroot:/root
      - /srv/minecraft/toast/data:/data
      - /srv/minecraft/toast/ssh:/etc/ssh
    ports:
      - target: 22
        published: 2230
        mode: ingress
      - target: 25565
        published: 25581
        mode: ingress
    networks:
      - minecraft

networks:
  minecraft:
    driver: overlay
  publicweb:
    driver: overlay
    external: true
