---
apiVersion: v1
kind: Secret
metadata:
  name: meilisearch-master-key
type: Opaque
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-meilisearch-sea1
spec:
  type: kv-v2
  mount: secret
  path: app/meilisearch/sea1
  destination:
    name: meilisearch-master-key
    create: false
  refreshAfter: 1m
