version: "3.6"
services:
  jenkins:
    image: registry.nepeat.com/jenkins
    build: .
    volumes:
      - /srv/var/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - publicweb
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:jenkins.generalprogramming.org
      restart_policy:
        condition: any

networks:
  publicweb:
    driver: overlay
    external: true
