server_name: "owo.me"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
  - port: 8000
    type: metrics
enable_metrics: true
database:
  name: psycopg2
  args:
    user: SECRET_database_user
    password: SECRET_database_password
    dbname: SECRET_database_name
    host: SECRET_database_host
    port: SECRET_database_port
log_config: "/config/log.yaml"
media_store_path: /data/media_store
max_upload_size: "99M"
registration_shared_secret: "SECRET_registration_shared_secret"
report_stats: false
macaroon_secret_key: "SECRET_macaroon_secret_key"
form_secret: "SECRET_form_secret"
signing_key_path: "/secrets/signing.key"
trusted_key_servers:
  - server_name: "matrix.org"
public_baseurl: https://matrix.owo.me
password_config:
  enabled: false
ip_range_whitelist: []
allow_public_rooms_over_federation: true
matrix_authentication_service:
  enabled: true

  # Internal URL where Synapse can reach MAS (must expose the discovery and oauth resources)
  endpoint: http://mas:8080/

  # Matches the `matrix.secret` in the auth service config
  secret: "SECRET_ADMIN_SECRET"
