global:
  scrape_interval:     10s
  evaluation_interval: 25s
  external_labels:
    host: docker
    replica: A

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
        - '192.168.3.1:9100'
        - '192.168.3.2:9100'
        - 'nhome.hosts.generalprogramming.org:9100'
  - job_name: "node_rpan"
    static_configs:
      - targets:
        - '192.168.3.1:8000'
        labels:
          group: 'rpan-group'
    scrape_interval: 1s
