version: "3"

services:
    sbot:
        image: ahdinosaur/ssb-pub
        ports:
            - "8008:8008"
        volumes:
            - "/srv/ssb-pub:/home/node/.ssb/"
            - "./ssb-config.json:/home/node/.ssb/config"
        networks:
            - app
            - publicweb
        deploy:
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    memory: 2048M
            placement:
                constraints:
                    - node.hostname == tcrp.catgirls.dev
networks:
    app:
        driver: overlay
    publicweb:
        driver: overlay
        external: true
