---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-oidc
    app.kubernetes.io/part-of: argocd
  name: argocd-oidc
  namespace: argocd
type: Opaque
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-oidc
  labels:
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/name: argocd-oidc
spec:
  type: kv-v2
  mount: secret
  path: app/argocd/sea1/oidc
  destination:
    name: argocd-oidc
    create: false
  refreshAfter: 1m
