---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-oidc
spec:
  type: kv-v2
  mount: secret
  path: app/argocd/oidc-secret/sea1/oidc
  destination:
    name: argocd-oidc
    create: true
  refreshAfter: 1m
