---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-oidc
  labels:
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/name: argocd-oidc
spec:
  type: kv-v2
  mount: secret
  path: app/argocd/sea1/oidc
  destination:
    name: argocd-oidc
    create: true
  refreshAfter: 1m
