apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  url: https://fmt2-argo.generalprogramming.org
  dex.config: |
    logger:
      level: debug
    connectors:
    - type: oidc
      id: vault
      name: Vault
      config:
        issuer: http://10.65.67.27:8201/v1/identity/oidc/provider/default
        clientID: vzs7h6HINWYepuD9A09RfKbn5owAIAfE
        clientSecret: hvo_secret_xn0vuvVfjITei4lMIyhbPqXi0Qp4UoJXagb0eBsGUOga7l8DSYRBbebMBDzzog1P
        insecureEnableGroups: true
        insecureSkipEmailVerified: true
        scopes:
        - user
        claimMapping:
          preferred_username: username
          email: username
        userNameKey: username
