apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-init
data:
  initialize-secrets.py: |
    #!/usr/bin/python
    import os
    import sys

    for f in sys.argv[1:]:
      with open(f"/config/{f}") as r:
        c = r.read()

      for k, v in os.environ.items():
        secret_key = f"SECRET_{k}"
        if secret_key not in c:
          continue

        if v is not None:
          c = c.replace(secret_key, v)
          print(f"adding environ '{k}'")

      with open(f"/data/{f}", 'w') as w:
        w.write(c)
