- hosts: database
  become: true
  roles:
     - role: setup_postgres
       postgres_hba_hosts:
         - "host    all             all             172.16.0.0/12           md5"
         - "host    all             all             192.168.0.0/16          md5"
    - role: ansible-elasticsearch
      es_major_version: "6.x"
      es_version: 6.6.0
      es_instance_name: 'elklog_{{ ansible_hostname | replace("-", "_") }}'
      es_data_dirs: "/var/lib/elasticsearch"
      es_log_dir: "/var/log/elasticsearch"
      es_config: {
        node.name: 'elklog_{{ ansible_hostname | replace("-", "_") }}',
        cluster.name: "elklog",
        network.host: "192.168.3.2",
        http.port: 9200,
        bootstrap.memory_lock: true
      }
      es_enable_xpack: true
      es_xpack_features:
        - alerting
        - monitoring
        - graph
      when: is_elastic_host
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 4g
    es_api_port: 9200
