---
- name: "Telegraf - Apt repo"
  apt_repository:
    repo: '{{ item }}'
    state: present
  loop:
    - 'deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable'

- name: "Telegraf - install"
  package:
    name: telegraf
    state: latest

- name: "Telegraf - config telegraf"
  template:
    src: "telegraf.j2"
    dest: "/etc/telegraf/telegraf.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  register: telegraf_config

- name: "Telegraf - Update systemd daemons configuration and restart daemons"
  systemd:
    name: telegraf
    enabled: true
    state: restarted
    daemon_reload: yes
  when: telegraf_config.changed
