apiVersion: v1
kind: ConfigMap
metadata:
  name: openviking-config
data:
  ov.conf: |
    {
      "storage": {
        "workspace": "/app/.openviking/openviking_workspace",
        "vectordb": {
          "name": "context",
          "backend": "local",
          "project": "default"
        },
        "agfs": {
          "backend": "local",
          "timeout": 10
        }
      },
      "log": {
        "level": "INFO",
        "output": "stdout"
      },
      "server": {
        "host": "0.0.0.0",
        "port": 1933,
        "workers": 1,
        "root_api_key": "${OPENVIKING_ROOT_API_KEY}",
        "cors_origins": ["*"]
      },
      "embedding": {
        "max_concurrent": 10,
        "dense": {
          "provider": "openai",
          "api_base": "https://openrouter.ai/api/v1",
          "api_key": "${OPENVIKING_OPENROUTER_API_KEY}",
          "model": "qwen/qwen3-embedding-8b",
          "dimension": 4096,
          "encoding_format": "float",
          "extra_headers": {
            "HTTP-Referer": "https://viking.owo.me",
            "X-Title": "OpenViking"
          }
        }
      },
      "vlm": {
        "provider": "openai",
        "api_base": "https://openrouter.ai/api/v1",
        "api_key": "${OPENVIKING_OPENROUTER_API_KEY}",
        "model": "minimax/minimax-m3",
        "max_retries": 2,
        "max_concurrent": 100,
        "extra_headers": {
          "HTTP-Referer": "https://viking.owo.me",
          "X-Title": "OpenViking"
        }
      }
    }
