---

- name: "Settings - Set swappiness to 0"
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
    reload: true

- name: "Settings - Enable kernel IP forwarding for app server."
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true
  when: appserver

- name: "Settings - Enable kernel IP forwarding for not app servers."
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    state: present
    reload: true
  when: not appserver

- name: "Settings - IPTables Save"
  shell: iptables-save > /etc/iptables.rules

- name: "Settings - Update global byobu statusrc"
  copy:
    src: byobu_status
    dest: /usr/share/byobu/status/status
    owner: root
    group: root
    mode: 0644

- name: "Settings - Restart rsyslog daemon"
  systemd:
    name: rsyslog
    enabled: true
    state: restarted
  when: rsyslog_config.changed

- name: "Settings - Set timezone to UTC"
  timezone:
    name: UTC
