apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-helm
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        global:
          name: fmt2
          datacenter: fmt2
        server:
          enabled: false
        client:
          enabled: true
          exposeGossipPorts: true
          join:
            # consul servers on the fmt2 hypervisors
            - "10.65.67.100"
            - "10.65.67.101"
            - "10.65.67.102"
            - "10.65.67.103"
            - "10.65.67.104"
