# Consul service configuration
- name: "Check if Consul config folder exists."
  ansible.builtin.stat:
    path: "/etc/consul.d/"
  register: consul_folder

- name: "Add node_exporter Consul service."
  ansible.builtin.copy:
    src: service_node_exporter.hcl
    dest: /etc/consul.d/service_node_exporter.hcl
    owner: root
    group: root
    mode: 0644
  when: node_exporter_port.failed == false and consul_folder.stat.exists == true

# folder setup
- name: "Create node_exporter folder"
  ansible.builtin.file:
    path: /var/lib/node_exporter
    state: directory
    owner: root
    group: root
    mode: 0755
  when: node_exporter_port.failed == false

# smartmon service
# - name: "Install smartmon script"
#   ansible.builtin.copy:
#     src: prom_smartmon.sh
#     dest: /usr/local/bin/prom_smartmon.sh
#     owner: root
#     group: root
#     mode: 0755

# - name: "Setup smartmon cronjob"
#   ansible.builtin.cron:
#     name: "prom_smartmon"
#     minute: "*"
#     job: "/usr/local/bin/prom_smartmon.sh > /var/lib/node_exporter/smartmon.prom.tmp && mv /var/lib/node_exporter/smartmon.prom.tmp /var/lib/node_exporter/smartmon.prom >/dev/null 2>&1"
#     user: root
#   when: "'metal' in group_names"

# ipmi scraper
# - name: "Install ipmi scraper script"
#   ansible.builtin.copy:
#     src: prom_ipmi.sh
#     dest: /usr/local/bin/prom_ipmi.sh
#     owner: root
#     group: root
#     mode: 0755

# - name: "Setup ipmi scraper cronjob"
#   ansible.builtin.cron:
#     name: "prom_ipmi"
#     minute: "*"
#     job: "ipmitool sensor | /usr/local/bin/prom_ipmi.sh > /var/lib/node_exporter/ipmi_sensors.prom.tmp && mv /var/lib/node_exporter/ipmi_sensors.prom.tmp /var/lib/node_exporter/ipmi_sensors.prom >/dev/null 2>&1"
#     user: root
#   when: "'metal' in group_names"
