system_info:
  default_user:
    groups:
      - docker

groups:
  - docker

runcmd:
  # Run provisioning playbooks
  - 'git clone https://github.com/general-programming/megarepo.git /root/megarepo'
  - '/bin/bash -c "cd /root/megarepo/automation/ansible && git pull && ansible-galaxy install -r roles.yml && ansible-playbook -c local -i inventory/localhost_app oneoff_cluster.yml"'
