system_info:
  default_user:
    groups:
      - docker

groups:
  - docker

runcmd:
  # Run pyinfra playbooks
  - 'git clone https://github.com/general-programming/megarepo.git /root/megarepo'
  - 'cp /tmp/pyinfra_all.py /root/megarepo/automation/pyinfra/group_data/all.py'
  - '/bin/bash -c "cd /root/megarepo/automation/pyinfra && APPROLE_EXISTS=1 /root/pyenv/bin/pyinfra -vv @local deploy_all.py"'
  - '/bin/bash -c "cd /root/megarepo/automation/ansible && git pull && ansible-galaxy install -r roles.yml && ansible-playbook -c local -i inventory/localhost_app oneoff_cluster.yml"'
