system_info:
  default_user:
    groups:
      - docker

groups:
  - docker

runcmd:
  # System setup
  - DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=-1 -y install git
  - 'git clone https://github.com/general-programming/megarepo.git /root/megarepo'
  - /root/megarepo/automation/deploy_server/common/00-install-packages.sh
  - /root/megarepo/automation/deploy_server/common/01-setup-swap.sh
  - /root/megarepo/automation/deploy_server/common/10-sysctl.sh
  - KEEP_NETCLIENT=1 /root/megarepo/automation/deploy_server/common/
  - systemctl start netclient
  # provisioning
  - '/bin/bash -c "cd /root/megarepo/automation/ansible && git pull && ansible-galaxy install -r roles.yml && ansible-playbook -c local -i inventory/localhost_app oneoff_cluster.yml"'
