# Push-only Attic token (`atticadm make-token --sub nix-cache-builder
# --pull general-programming --push general-programming`); see README.md.
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-nix-cache-builder
spec:
  type: kv-v2
  mount: secret
  path: app/nix-cache-builder
  destination:
    name: nix-cache-builder
    create: true
  refreshAfter: 1h
