version: "3.8"
services:
  znc:
    image: znc
    build: .
    volumes:
      - /srv/var/znc:/znc-data
    ports:
      - 6697:6697
    deploy:
      restart_policy:
        condition: any

networks:
  publicweb:
    driver: overlay
    external: true
