version: "3.8"
services:
  znc:
    image: znc:1.8.2
    volumes:
      - /mnt/ceph/var/znc:/znc-data
    ports:
      - target: 6667
        published: 6667
        mode: ingress
      - target: 6697
        published: 6697
        mode: ingress
    deploy:
      restart_policy:
        condition: any
