apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mastodon-coolmathgames
resources:
  - "database.yaml"
  - "es-certificates.yaml"
helmCharts:
  - name: mastodon
    releaseName: mastodon
    repo: https://codeberg.org/api/packages/open-engineering/helm
    version: 13.0.5
    valuesFile: mastodon-values.yaml
    namespace: mastodon-coolmathgames
images:
  - name: docker.io/bitnami/redis
    newName: docker.io/bitnamilegacy/redis
patches:
  - path: patch-chewy-upgrade-es-pass.yaml
    target:
      kind: Job
      name: mastodon-chewy-upgrade
