apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mastodon-coolmathgames
resources:
  - "database.yaml"
helmCharts:
  - name: mastodon
    releaseName: mastodon
    repo: https://codeberg.org/api/packages/open-engineering/helm
    version: 13.0.0
    valuesFile: mastodon-values.yaml
    namespace: mastodon-coolmathgames
images:
  - name: docker.io/bitnami/redis
    newName: docker.io/bitnamilegacy/redis
