// Code generated by Kitex v0.4.4. DO NOT EDIT.

package tunnelservice

import (
	server "github.com/cloudwego/kitex/server"
	tunneler "github.com/general-programming/megarepo/clients/infra_network_tunneler/kitex_gen/infra/network/tunneler"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler tunneler.TunnelService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
