version: "3.6"
services:
  broker:
    image: rabbitmq:alpine
    environment:
      RABBITMQ_DEFAULT_USER: mayan
      RABBITMQ_DEFAULT_PASS: mayan
      RABBITMQ_DEFAULT_VHOST: mayan
    volumes:
      - /srv/var/mayan/rabbitmq:/var/lib/rabbitmq
    networks:
      - mayan

  results:
    image: redis:alpine
    volumes:
      - /srv/var/mayan/results_redis:/data
    networks:
      - mayan

  mayan-edms:
    image: mayanedms/mayanedms:latest
    environment:
      MAYAN_CELERY_BROKER_URL: amqp://mayan:mayan@broker:5672/mayan
      MAYAN_CELERY_RESULT_BACKEND: redis://results:6379/0
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_WORKER_FAST_CONCURRENCY: 0
      MAYAN_WORKER_MEDIUM_CONCURRENCY: 0
      MAYAN_WORKER_SLOW_CONCURRENCY: 0
    env_file: .env
    volumes:
      - /srv/var/mayan/data:/var/lib/mayan
      - /srv/var/mayan/watch_folder:/srv/watch_folder
    deploy:
      labels:
        - traefik.enable=true
        - traefik.port=8000
        - traefik.docker.network=publicweb
        # Routes
        - traefik.frontend.rule=Host:mayan.generalprogramming.org
      restart_policy:
        condition: any
    networks:
      - publicweb
      - mayan

networks:
  publicweb:
    driver: overlay
    external: true
  mayan:
    driver: overlay
