version: "3.8"
services:
  traefik:
    image: traefik:v2.6.0
    env_file: .env
    command:
      - traefik

      # static config provider
      - --providers.file.directory=/config
      - --providers.file.watch=true

      # acme json
      - --certificatesResolvers.main.acme.storage=/var/lib/traefik/acme.json

      # entrypoint http
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https

      # entrypoint https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.options=default@file

      # api
      - --api=true
      - --api.dashboard=true

      # ping
      - --ping.entryPoint=http

      # docker swarm provider
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --providers.docker.defaultRule="Host(`{{ .Name }}.thonk.dev`)"
      - --providers.docker.swarmMode=true

      # consul provider
      # - --providers.consul.endpoints=consul.service.fmt2.consul.:8500

      # consul catalog provider
      - --providers.consulcatalog.endpoint.address=consul.service.fmt2.consul:8500
      - --providers.consulcatalog.exposedByDefault=false
      - --providers.consulcatalog.defaultRule="Host(`{{ .Name }}.thonk.dev`)"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/etc/traefik:/config
      - /var/lib/traefik:/var/lib/traefik
    networks:
      - publicweb
      - traefik
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

networks:
  publicweb:
    driver: overlay
    external: true
  traefik:
    driver: overlay
