version: "3.8"
services:
  traefik:
    image: traefik:v2.11.20
    env_file: .env
    command:
      - traefik

      # static config provider
      - --providers.file.directory=/config
      - --providers.file.watch=true

      # acme json
      - --certificatesresolvers.main.acme.email=support@generalprogramming.org
      - --certificatesResolvers.main.acme.storage=/var/lib/traefik/acme.json
      - --certificatesresolvers.main.acme.dnschallenge=true
      - --certificatesresolvers.main.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.main.acme.dnschallenge.delaybeforecheck=0
      - --certificatesresolvers.main.acme.httpchallenge=false

      # entrypoint http
      - --entrypoints.http.address=:80

      # entrypoint https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.certResolver=main
      - --entrypoints.https.http.tls.domains[0].main=nepeat.com
      - --entrypoints.https.http.tls.domains[0].sans=*.nepeat.com
      - --entrypoints.https.http.tls.domains[1].main=thonk.dev
      - --entrypoints.https.http.tls.domains[1].sans=*.thonk.dev
      - --entrypoints.https.http.tls.domains[2].main=generalprogramming.org
      - --entrypoints.https.http.tls.domains[2].sans=*.generalprogramming.org
      - --entrypoints.https.http.tls.domains[3].main=owo.me
      - --entrypoints.https.http.tls.domains[3].sans=*.owo.me

      # api
      - --api=true
      - --api.dashboard=true

      # ping
      - --ping.entryPoint=http

      # consul catalog provider
      - --providers.consulcatalog=true
      - --providers.consulcatalog.endpoint.address=consul.service.sea420.consul.:8500
      - --providers.consulcatalog.exposedByDefault=false
      - --providers.consulcatalog.defaultRule=Host(`{{ .Name }}.thonk.dev`)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/etc/traefik:/config
      - /var/lib/traefik:/var/lib/traefik
    networks:
      - publicweb
      - traefik
    ports:
      - target: 80
        published: 80
        mode: ingress
      - target: 443
        published: 443
        mode: ingress
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
networks:
  publicweb:
    driver: overlay
    external: true
  traefik:
    driver: overlay
