global: {}
serversTransport:
  insecureSkipVerify: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
    http:
      tls:
        certResolver: default

  internal:
    address: :8080
    http:
      routers:
        api:
          rule: Host(`traefik.generalprogramming.org`)
          service: api@internal
          middlewares:
            - apiauth
      middlewares:
        apiauth:
          basicAuth:
            usersFile: /traefik_users.passwd
            realm: "genprog traefik"

providers:
  providersThrottleDuration: 2s

  consul:
    endpoints:
      - "consul.service.dc1.consul:8500"
    rootKey: "traefik"

  consulCatalog:
    endpoint:
      address: "consul.service.dc1.consul:8500"
    exposedByDefault: false
    defaultRule: "Host(`{{ .Name }}.thonk.dev`)"

  docker:
    watch: true
    swarmMode: true
    swarmModeRefreshSeconds: 15s
    defaultRule: "Host(`{{ .Name }}.thonk.dev`)"

  file:
    watch: true
    filename: /rules.toml

api:
  dashboard: true

ping:
  entryPoint: http

log:
  level: INFO

certificatesResolvers:
  default:
    acme:
      email: nepeat@gmail.com
      storage: traefik/acme/account
      dnsChallenge:
        provider: cloudflare
      httpChallenge:
        entryPoint: http
