apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akvorado
resources:
  - clickhouse.yaml
  - kafka.yaml
  - valkey.yaml
  - config.yaml
  - orchestrator.yaml
  - inlet.yaml
  - outlet.yaml
  - console.yaml
