version: '3.7'
services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
  logstream:
    build: .
    environment:
      REDIS_URL: redis://redis:6379
      PUSH_REDIS: "true"
      PUSH_INFLUX: "true"
    restart: always
    env_file:
      - .env
volumes:
  redis-data:
