---
apiVersion: v1
kind: Namespace
metadata:
  name: coder
  labels:
    kubernetes.io/metadata.name: coder
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
