---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescale
spec:
  images:
    - major: 17
      image: timescale/timescaledb-ha:pg17.9-ts2.25.2-all
    - major: 18
      image: timescale/timescaledb-ha:pg18.3-ts2.25.2-all
