name = "mailhook"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-04-19"

browser = { binding = "MYBROWSER" }

[observability.logs]
enabled = true

[vars]
BUCKET_BASE = "https://mailhook.owo.me"

[[r2_buckets]]
binding = 'MY_BUCKET'    # <~ valid JavaScript variable name
bucket_name = 'mailhook'

[[queues.producers]]
queue = "email-queue"
binding = "EMAIL_QUEUE"

[[queues.consumers]]
queue = "email-queue"
