# SPDX-License-Identifier: GPL-2.0
#
# Out-of-tree build of a modified nvme-core.ko. Only nvme-core is rebuilt:
# nvme.ko (pci.c), nvme-fabrics, nvme-tcp etc. stay stock, because none of
# the exported prototypes change and therefore neither do their symbol CRCs.

ccflags-y				+= -I$(src)

obj-m					+= nvme-core.o

nvme-core-y				+= core.o ioctl.o sysfs.o pr.o noreset.o
nvme-core-$(CONFIG_NVME_VERBOSE_ERRORS)		+= constants.o
nvme-core-$(CONFIG_TRACING)			+= trace.o
nvme-core-$(CONFIG_NVME_MULTIPATH)		+= multipath.o
nvme-core-$(CONFIG_BLK_DEV_ZONED)		+= zns.o
nvme-core-$(CONFIG_FAULT_INJECTION_DEBUG_FS)	+= fault_inject.o
nvme-core-$(CONFIG_NVME_HWMON)			+= hwmon.o
nvme-core-$(CONFIG_NVME_HOST_AUTH)		+= auth.o
