global:
  scrape_interval: 10s
  evaluation_interval: 30s
  external_labels:
    host: docker
    replica: A

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          - "storage-conejar.catgirls.dev:9100"
          - "10.65.67.170:9121"
          - "10.65.67.170:9122"
  - job_name: "consul"
    consul_sd_configs:
      - server: "consul.service.dc1.consul:8500"
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,prometheus,.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job
