---
- name: "filebeat - Install GPG key"
  apt_key:
    url: '{{ item.key }}'
    id: '{{ item.value }}'
    state: present
  with_dict:
      "https://artifacts.elastic.co/GPG-KEY-elasticsearch": "D88E42B4"

- name: "filebeat - Configure repo"
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present

- name: "filebeat - Install"
  apt:
    name: filebeat
    state: latest
    update_cache: yes
    cache_valid_time: 172800

- name: "filebeat - Update config"
  template:
    src: filebeat.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0600
    owner: 'root'
    group: 'root'
  register: config_rsync

- name: "filebeat - Update systemd daemon configuration and restart daemon"
  systemd:
    name: filebeat
    enabled: true
    state: restarted
    daemon_reload: yes
