version: '2'
services:
  fluentd:
    build:
      context: ./
      dockerfile: Dockerfile_fluentd
    restart: always
    environment:
      SERVICE_NAME: fluentd
      FLUENTD_OPT: '-v'
    ports:
      - '192.168.10.1:24224:24224'
      - '192.168.10.1:24224:24224/udp'
      - '192.168.10.1:5140:5140'
      - '192.168.10.1:5140:5140/udp'
      - '127.0.0.1:5140:5140'
      - '127.0.0.1:5140:5140/udp'
