FROM fluent/fluentd:latest

RUN apk add --no-cache --virtual .build-deps sudo build-base ruby-dev && \
    fluent-gem install fluent-plugin-elasticsearch fluent-plugin-rewrite-tag-filter \
    fluent-plugin-slack fluent-plugin-genhashvalue fluent-plugin-grok-parser && \
    sudo gem sources --clear-all && \
    apk del .build-deps && \
    rm -rf /home/fluent/.gem/ruby/2.3.0/cache/*.gem

EXPOSE 24224
EXPOSE 24224/udp
EXPOSE 5140
EXPOSE 5140/udp

COPY custompatterns/ /fluentd/etc/custompatterns/
COPY fluent.conf /fluentd/etc/
COPY fluent_conf.d/ /fluentd/etc/conf.d/
