// Code generated by Kitex v0.4.4. DO NOT EDIT.

package tunnelservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	tunneler "github.com/general-programming/megarepo/services/infra_network_tunneler/kitex_gen/infra/network/tunneler"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetTunnel(ctx context.Context, req *tunneler.GetTunnelRequest, callOptions ...callopt.Option) (r *tunneler.GetTunnelResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTunnelServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTunnelServiceClient struct {
	*kClient
}

func (p *kTunnelServiceClient) GetTunnel(ctx context.Context, req *tunneler.GetTunnelRequest, callOptions ...callopt.Option) (r *tunneler.GetTunnelResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTunnel(ctx, req)
}
