// Code generated by Kitex v0.4.4. DO NOT EDIT.
package tunnelservice

import (
	server "github.com/cloudwego/kitex/server"
	tunneler "github.com/general-programming/megarepo/services/infra_network_tunneler/kitex_gen/infra/network/tunneler"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler tunneler.TunnelService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
