apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: akvorado
resources:
  - ../base
  - secret.yaml
  - flow-lb.yaml
  - inlet-netpol.yaml
  - clickhouse-netpol.yaml
  - datastore-netpol.yaml
  - ingress.yaml
patches:
  - path: inlet-nodes.yaml
