---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: connector-fmt2
spec:
  replicas: 2
  hostnamePrefix: connector-fmt2
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - "10.65.67.0/24"
      - "10.255.1.0/24"
