---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - database.yaml
  - redis.yaml
  - obc.yaml
helmCharts:
  - name: harbor
    releaseName: harbor
    namespace: harbor
    repo: https://helm.goharbor.io
    version: 1.19.2
    valuesFile: values.yaml
