---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: coder-db
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql-standard-trixie
    major: 18
  instances: 2
  primaryUpdateStrategy: unsupervised
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: generalprogramming.org/no-database
                operator: DoesNotExist
  storage:
    storageClass: local-path
    size: 16Gi
  bootstrap:
    initdb:
      database: coder
      owner: coder
