version: "3.6"
services:
  unrealircd:
    image: quay.io/nepeat/unrealircd:latest
    build: .
    volumes:
      - /etc/unrealircd:/etc/unrealircd
    network_mode: host
    deploy:
      restart_policy:
        condition: always
