---
- name: "Admin user - See if user exists"
  getent:
    database: passwd
    key: "{{ admin_user }}"
    fail_key: false

- name: "Admin user - Create"
  user:
    name: "{{ admin_user }}"
    groups: "{{ item }}"
    shell: /bin/zsh
  when: not getent_passwd[admin_user]
  with_items:
    - sudo

- name: "Admin user - Add optional groups"
  user:
    name: "{{ admin_user }}"
    groups: "{{ item }}"
    append: true
  with_items:
    - docker
  ignore_errors: yes

- name: "Admin user - Update SSH keys"
  authorized_key:
    user: "{{ admin_user }}"
    state: present
    key: "{{ admin_ssh_keys | join('\n') }}"
    exclusive: true

- name: "Admin user - Enable byobu"
  shell: "byobu-enable"
  args:
    creates: "/home/{{ admin_user }}/.byobu"
  become_user: "{{ admin_user }}"

- name: "Admin user - Ubuntu sudoers NOPASSWD"
  copy:
    src: sudoers_ubuntu
    dest: /etc/sudoers.d/ubuntu
    owner: root
    group: root
    mode: 0440
